-- Agrega columna para controlar la expiracion del codigo de verificacion (10 minutos)
IF NOT EXISTS (
    SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_NAME = 'TB_USUARIO' AND COLUMN_NAME = 'FECHA_CODIGO_VERIFICACION'
)
BEGIN
    ALTER TABLE dbo.TB_USUARIO
    ADD FECHA_CODIGO_VERIFICACION DATETIME NULL;
END
