-- Agrega columnas para el flujo de cambio de correo pendiente
-- Correr una sola vez en BD
IF NOT EXISTS (
    SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_SCHEMA = 'dbo'
      AND TABLE_NAME = 'TB_USUARIO'
      AND COLUMN_NAME = 'CORREO_PENDIENTE'
)
BEGIN
    ALTER TABLE dbo.TB_USUARIO
    ADD CORREO_PENDIENTE NVARCHAR(150) NULL;
END

IF NOT EXISTS (
    SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_SCHEMA = 'dbo'
      AND TABLE_NAME = 'TB_USUARIO'
      AND COLUMN_NAME = 'CODIGO_CAMBIO_CORREO'
)
BEGIN
    ALTER TABLE dbo.TB_USUARIO
    ADD CODIGO_CAMBIO_CORREO NVARCHAR(100) NULL;
END

IF NOT EXISTS (
    SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_SCHEMA = 'dbo'
      AND TABLE_NAME = 'TB_USUARIO'
      AND COLUMN_NAME = 'FECHA_CODIGO_CORREO'
)
BEGIN
    ALTER TABLE dbo.TB_USUARIO
    ADD FECHA_CODIGO_CORREO DATETIME NULL;
END
