-- Reemplaza GUID_USUARIO por DISPOSITIVO en TB_BITACORA y actualiza SP_INSERTAR_BITACORA.
-- Correr UNA SOLA VEZ en BD.

-- Paso 1: Agregar columna DISPOSITIVO si no existe
IF NOT EXISTS (
    SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_NAME = 'TB_BITACORA' AND COLUMN_NAME = 'DISPOSITIVO'
)
BEGIN
    ALTER TABLE dbo.TB_BITACORA
    ADD DISPOSITIVO NVARCHAR(200) NULL;
END

-- Paso 2: Eliminar columna GUID_USUARIO si existe
IF EXISTS (
    SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_NAME = 'TB_BITACORA' AND COLUMN_NAME = 'GUID_USUARIO'
)
BEGIN
    ALTER TABLE dbo.TB_BITACORA
    DROP COLUMN GUID_USUARIO;
END
GO

-- Paso 3: Actualizar el SP para usar DISPOSITIVO en lugar de GUID_USUARIO
CREATE OR ALTER PROCEDURE dbo.SP_INSERTAR_BITACORA
(
    @DISPOSITIVO  NVARCHAR(200),
    @CLASE        NVARCHAR(100),
    @METODO       NVARCHAR(100),
    @TIPO         SMALLINT,
    @CODIGO_ERROR INT,
    @DESCRIPCION  NVARCHAR(MAX),
    @REQUEST      NVARCHAR(MAX),
    @RESPONSE     NVARCHAR(MAX)
)
AS
BEGIN
    SET NOCOUNT ON;
    BEGIN TRY
        INSERT INTO dbo.TB_BITACORA
            (DISPOSITIVO, CLASE, METODO, TIPO, CODIGO_ERROR, DESCRIPCION, REQUEST, RESPONSE, FECHA)
        VALUES
            (@DISPOSITIVO, @CLASE, @METODO, @TIPO, @CODIGO_ERROR, @DESCRIPCION, @REQUEST, @RESPONSE, GETDATE());
    END TRY
    BEGIN CATCH
        -- La bitácora no debe bloquear el flujo principal
    END CATCH
END
