CREATE OR ALTER PROCEDURE dbo.SP_ELIMINAR_TARIFA
    @GUID_TARIFA      UNIQUEIDENTIFIER,
    @IDRETURN         INT OUTPUT,
    @ERRORID          INT OUTPUT,
    @ERRORDESCRIPCION NVARCHAR(MAX) OUTPUT
AS
BEGIN
    SET NOCOUNT ON;

    BEGIN TRY
        DECLARE @ID_TARIFA INT;

        SELECT @ID_TARIFA = ID_TARIFA
        FROM dbo.TB_TARIFA
        WHERE GUID_TARIFA = @GUID_TARIFA;

        IF @ID_TARIFA IS NULL
        BEGIN
            SET @IDRETURN = 0;
            SET @ERRORID = 3;
            SET @ERRORDESCRIPCION = 'Tarifa no encontrada';
            RETURN;
        END

        UPDATE dbo.TB_TARIFA
        SET ESTADO = 0
        WHERE ID_TARIFA = @ID_TARIFA;

        SET @IDRETURN = 1;
        SET @ERRORID = 0;
        SET @ERRORDESCRIPCION = NULL;
    END TRY
    BEGIN CATCH
        SET @IDRETURN = 0;
        SET @ERRORID = ERROR_NUMBER();
        SET @ERRORDESCRIPCION = ERROR_MESSAGE();
    END CATCH
END
GO
