CREATE OR ALTER PROCEDURE dbo.SP_ELIMINAR_HORARIO
    @GUID_HORARIO     UNIQUEIDENTIFIER,
    @IDRETURN         INT OUTPUT,
    @ERRORID          INT OUTPUT,
    @ERRORDESCRIPCION NVARCHAR(MAX) OUTPUT
AS
BEGIN
    SET NOCOUNT ON;

    BEGIN TRY
        DECLARE @ID_HORARIO INT;

        SELECT @ID_HORARIO = ID_HORARIO
        FROM dbo.TB_HORARIO
        WHERE GUID_HORARIO = @GUID_HORARIO;

        IF @ID_HORARIO IS NULL
        BEGIN
            SET @IDRETURN = 0;
            SET @ERRORID = 3;
            SET @ERRORDESCRIPCION = 'Horario no encontrado';
            RETURN;
        END

        UPDATE dbo.TB_HORARIO
        SET ESTADO = 0
        WHERE ID_HORARIO = @ID_HORARIO;

        SET @IDRETURN = 1;
        SET @ERRORID = 0;
        SET @ERRORDESCRIPCION = NULL;
    END TRY
    BEGIN CATCH
        SET @IDRETURN = 0;
        SET @ERRORID = ERROR_NUMBER();
        SET @ERRORDESCRIPCION = ERROR_MESSAGE();
    END CATCH
END
GO
