-- SP_ELIMINAR_USUARIO: elimina una cuenta y limpia dependencias directas.
-- Conserva la bitacora, pero la desasocia del usuario para no romper la FK.
CREATE OR ALTER PROCEDURE dbo.SP_ELIMINAR_USUARIO
(
    @GUID_USUARIO     UNIQUEIDENTIFIER,
    @IDRETURN         INT OUTPUT,
    @ERRORID          INT OUTPUT,
    @ERRORDESCRIPCION NVARCHAR(MAX) OUTPUT
)
AS
BEGIN
    SET NOCOUNT ON;

    BEGIN TRY
        DECLARE @ID_USUARIO BIGINT;

        SELECT @ID_USUARIO = ID_USUARIO
        FROM dbo.TB_USUARIO
        WHERE GUID_USUARIO = @GUID_USUARIO;

        IF @ID_USUARIO IS NULL
        BEGIN
            SET @IDRETURN = -1;
            SET @ERRORID = 2;
            SET @ERRORDESCRIPCION = N'USUARIO NO REGISTRADO';
            RETURN;
        END

        BEGIN TRANSACTION;

        UPDATE dbo.TB_BITACORA
        SET ID_USUARIO = NULL
        WHERE ID_USUARIO = @ID_USUARIO;

        DELETE FROM dbo.TB_FAVORITO
        WHERE ID_USUARIO = @ID_USUARIO;

        DELETE FROM dbo.TB_HISTORIAL_VIAJE
        WHERE ID_USUARIO = @ID_USUARIO;

        DELETE FROM dbo.TB_SESION
        WHERE ID_USUARIO = @ID_USUARIO;

        DELETE FROM dbo.TB_USUARIO
        WHERE ID_USUARIO = @ID_USUARIO;

        COMMIT TRANSACTION;

        SET @IDRETURN = @ID_USUARIO;
        SET @ERRORID = 0;
        SET @ERRORDESCRIPCION = N'';
    END TRY
    BEGIN CATCH
        IF @@TRANCOUNT > 0
            ROLLBACK TRANSACTION;

        SET @IDRETURN = -1;
        SET @ERRORID = ERROR_NUMBER();
        SET @ERRORDESCRIPCION = ERROR_MESSAGE();

        INSERT INTO dbo.TB_ERROR_EN_BASE_DATOS(SEVERIDAD, STORED_PROCEDURE, NUMERO, DESCRIPCION, LINEA)
        SELECT ERROR_SEVERITY(), ERROR_PROCEDURE(), ERROR_NUMBER(), ERROR_MESSAGE(), ERROR_LINE();
    END CATCH
END
