ALTER PROCEDURE [dbo].[SP_ACTUALIZAR_RUTA]
(
    @GUID_RUTA        UNIQUEIDENTIFIER,
    @NOMBRE           NVARCHAR(200),
    @NUMERO_RUTA      NVARCHAR(20)     = NULL,
    @HORA_INICIO      TIME             = NULL,
    @HORA_FIN         TIME             = NULL,
    @ESTADO_SERVICIO  TINYINT          = NULL,
    @GUID_ZONA        UNIQUEIDENTIFIER = NULL,

    @IDRETURN         INT OUTPUT,
    @ERRORID          INT OUTPUT,
    @ERRORDESCRIPCION NVARCHAR(MAX) OUTPUT
)
AS
BEGIN
    SET NOCOUNT ON;
    BEGIN TRY
        DECLARE @ID_RUTA INT;
        SELECT @ID_RUTA = ID_RUTA FROM dbo.TB_RUTA WHERE GUID_RUTA = @GUID_RUTA;

        IF @ID_RUTA IS NULL
        BEGIN
            SET @IDRETURN = -1; SET @ERRORID = 12; SET @ERRORDESCRIPCION = N'RUTA NO EXISTE'; RETURN;
        END

        DECLARE @ID_ZONA INT = NULL;
        IF @GUID_ZONA IS NOT NULL
            SELECT @ID_ZONA = ID_ZONA FROM dbo.TB_ZONA WHERE GUID_ZONA = @GUID_ZONA;

        UPDATE dbo.TB_RUTA
        SET NOMBRE          = @NOMBRE,
            NUMERO_RUTA     = ISNULL(@NUMERO_RUTA, NUMERO_RUTA),
            HORA_INICIO     = ISNULL(@HORA_INICIO, HORA_INICIO),
            HORA_FIN        = ISNULL(@HORA_FIN, HORA_FIN),
            ESTADO_SERVICIO = ISNULL(@ESTADO_SERVICIO, ESTADO_SERVICIO),
            ID_ZONA         = @ID_ZONA
        WHERE ID_RUTA = @ID_RUTA;

        SET @IDRETURN = @ID_RUTA; SET @ERRORID = 0; SET @ERRORDESCRIPCION = N'';
    END TRY
    BEGIN CATCH
        SET @IDRETURN = -1; SET @ERRORID = ERROR_NUMBER(); SET @ERRORDESCRIPCION = ERROR_MESSAGE();

        INSERT INTO dbo.TB_ERROR_EN_BASE_DATOS(SEVERIDAD, STORED_PROCEDURE, NUMERO, DESCRIPCION, LINEA)
        SELECT ERROR_SEVERITY(), ERROR_PROCEDURE(), ERROR_NUMBER(), ERROR_MESSAGE(), ERROR_LINE();
    END CATCH
END
