ALTER PROCEDURE dbo.SP_ACTIVAR_USUARIO
(
    @CORREO_ELECTRONICO  NVARCHAR(100),
    @NUMERO_VERIFICACION NVARCHAR(MAX),
    @FILASACTUALIZADAS   INT OUTPUT,
    @IDRETURN            INT OUTPUT,
    @ERRORID             INT OUTPUT,
    @ERRORDESCRIPCION    NVARCHAR(MAX) OUTPUT
)
AS
BEGIN
    SET NOCOUNT ON;
    BEGIN TRY
        UPDATE dbo.TB_USUARIO
        SET
            ESTADO               = 1,
            NUMERO_VERIFICACION  = NULL
        WHERE
            CORREO_ELECTRONICO   = @CORREO_ELECTRONICO
            AND NUMERO_VERIFICACION = @NUMERO_VERIFICACION
            AND ESTADO           = 0;

        SET @FILASACTUALIZADAS = @@ROWCOUNT;
        SET @IDRETURN          = @FILASACTUALIZADAS;
        SET @ERRORID           = 0;
        SET @ERRORDESCRIPCION  = N'';
    END TRY
    BEGIN CATCH
        SET @FILASACTUALIZADAS = 0;
        SET @IDRETURN          = -1;
        SET @ERRORID           = ERROR_NUMBER();
        SET @ERRORDESCRIPCION  = ERROR_MESSAGE();
        INSERT INTO dbo.TB_ERROR_EN_BASE_DATOS(SEVERIDAD, STORED_PROCEDURE, NUMERO, DESCRIPCION, LINEA)
        SELECT ERROR_SEVERITY(), ERROR_PROCEDURE(), ERROR_NUMBER(), ERROR_MESSAGE(), ERROR_LINE();
    END CATCH
END
