-- ============================================================
-- FIX MÍNIMO: XACT_ABORT OFF + ROLLBACK en cada SP
-- ============================================================
-- PROBLEMA: LINQ envuelve el SP en transacción implícita.
--           Si el SP falla, XACT_STATE = -1 (transacción no
--           confirmable). Con XACT_ABORT ON (default), SQL mata
--           todo y C# recibe una excepción, no los OUTPUT params.
--
-- SOLUCIÓN MÍNIMA POR SP: solo 2 cambios por SP:
--   1. SET XACT_ABORT OFF  ? permite llegar al CATCH
--   2. IF XACT_STATE() <> 0 ROLLBACK  ? limpia la transacción
--      para que C# reciba los OUTPUT params correctamente
--
-- El INSERT a TB_ERROR_EN_BASE_DATOS lo hace C# desde Utilitarios
-- usando ADO.NET directo (sin LINQ, sin transacción).
-- Así no hay que repetir lógica en cada SP.
-- ============================================================

ALTER PROCEDURE dbo.SP_INGRESAR_USUARIO
(
    @NOMBRE              NVARCHAR(50),
    @APELLIDOS           NVARCHAR(50),
    @CORREO_ELECTRONICO  NVARCHAR(100),
    @PASSWORD            NVARCHAR(MAX),
    @NUMERO_VERIFICACION NVARCHAR(MAX),
    @GUID_USUARIO        UNIQUEIDENTIFIER OUTPUT,
    @IDRETURN            INT OUTPUT,
    @ERRORID             INT OUTPUT,
    @ERRORDESCRIPCION    NVARCHAR(MAX) OUTPUT
)
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT OFF;                          -- permite llegar al CATCH
    BEGIN TRY
        IF EXISTS (SELECT 1 FROM dbo.TB_USUARIO WHERE CORREO_ELECTRONICO = @CORREO_ELECTRONICO)
        BEGIN
            SET @IDRETURN = -1; SET @ERRORID = 1; SET @ERRORDESCRIPCION = N'CORREO YA REGISTRADO'; RETURN;
        END
        INSERT INTO dbo.TB_USUARIO
            (NOMBRE, APELLIDOS, CORREO_ELECTRONICO, [PASSWORD], ESTADO, FECHA_REGISTRO, NUMERO_VERIFICACION, FECHA_CODIGO_VERIFICACION)
        VALUES
            (@NOMBRE, @APELLIDOS, @CORREO_ELECTRONICO, @PASSWORD, 0, GETUTCDATE(), @NUMERO_VERIFICACION, GETUTCDATE());
        DECLARE @ID BIGINT = SCOPE_IDENTITY();
        SELECT @GUID_USUARIO = GUID_USUARIO FROM dbo.TB_USUARIO WHERE ID_USUARIO = @ID;
        SET @IDRETURN = @ID; SET @ERRORID = 0; SET @ERRORDESCRIPCION = N'';
    END TRY
    BEGIN CATCH
        IF XACT_STATE() <> 0 ROLLBACK;          -- limpia transacción rota
        SET @IDRETURN = -1; SET @ERRORID = ERROR_NUMBER(); SET @ERRORDESCRIPCION = ERROR_MESSAGE();
        -- C# (Utilitarios.registrarErrorBD) se encarga del INSERT a TB_ERROR_EN_BASE_DATOS
    END CATCH
END
GO

ALTER PROCEDURE dbo.SP_ACTIVAR_USUARIO
(
    @CORREO_ELECTRONICO  NVARCHAR(100),
    @NUMERO_VERIFICACION NVARCHAR(MAX),
    @FILASACTUALIZADAS   INT OUTPUT,
    @IDRETURN            INT OUTPUT,
    @ERRORID             INT OUTPUT,
    @ERRORDESCRIPCION    NVARCHAR(MAX) OUTPUT
)
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT OFF;
    BEGIN TRY
        IF NOT EXISTS (
            SELECT 1 FROM dbo.TB_USUARIO
            WHERE CORREO_ELECTRONICO = @CORREO_ELECTRONICO AND NUMERO_VERIFICACION = @NUMERO_VERIFICACION
              AND ESTADO = 0 AND FECHA_CODIGO_VERIFICACION IS NOT NULL
              AND DATEDIFF(MINUTE, FECHA_CODIGO_VERIFICACION, GETUTCDATE()) <= 10
        )
        BEGIN
            SET @FILASACTUALIZADAS = 0; SET @IDRETURN = -1; SET @ERRORID = 3; SET @ERRORDESCRIPCION = N'CODIGO INVALIDO O EXPIRADO'; RETURN;
        END
        UPDATE dbo.TB_USUARIO
        SET ESTADO = 1, NUMERO_VERIFICACION = NULL, FECHA_CODIGO_VERIFICACION = NULL
        WHERE CORREO_ELECTRONICO = @CORREO_ELECTRONICO AND NUMERO_VERIFICACION = @NUMERO_VERIFICACION AND ESTADO = 0;
        SET @FILASACTUALIZADAS = @@ROWCOUNT; SET @IDRETURN = @FILASACTUALIZADAS; SET @ERRORID = 0; SET @ERRORDESCRIPCION = N'';
    END TRY
    BEGIN CATCH
        IF XACT_STATE() <> 0 ROLLBACK;
        SET @FILASACTUALIZADAS = 0; SET @IDRETURN = -1; SET @ERRORID = ERROR_NUMBER(); SET @ERRORDESCRIPCION = ERROR_MESSAGE();
    END CATCH
END
GO

ALTER PROCEDURE dbo.SP_DESACTIVAR_USUARIO
(
    @GUID_USUARIO     UNIQUEIDENTIFIER,
    @IDRETURN         INT OUTPUT,
    @ERRORID          INT OUTPUT,
    @ERRORDESCRIPCION NVARCHAR(MAX) OUTPUT
)
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT OFF;
    BEGIN TRY
        DECLARE @ID_USUARIO BIGINT;
        SELECT @ID_USUARIO = ID_USUARIO FROM dbo.TB_USUARIO WHERE GUID_USUARIO = @GUID_USUARIO;
        IF @ID_USUARIO IS NULL
        BEGIN
            SET @IDRETURN = -1; SET @ERRORID = 2; SET @ERRORDESCRIPCION = N'USUARIO NO REGISTRADO'; RETURN;
        END
        UPDATE dbo.TB_USUARIO SET ESTADO = 2 WHERE ID_USUARIO = @ID_USUARIO;
        UPDATE dbo.TB_SESION
        SET ESTADO = 0, FECHA_FINAL = GETUTCDATE(), FECHA_ACTUALIZACION = GETUTCDATE()
        WHERE ID_USUARIO = @ID_USUARIO AND ESTADO = 1;
        SET @IDRETURN = @ID_USUARIO; SET @ERRORID = 0; SET @ERRORDESCRIPCION = N'';
    END TRY
    BEGIN CATCH
        IF XACT_STATE() <> 0 ROLLBACK;
        SET @IDRETURN = -1; SET @ERRORID = ERROR_NUMBER(); SET @ERRORDESCRIPCION = ERROR_MESSAGE();
    END CATCH
END
GO

CREATE OR ALTER PROCEDURE dbo.SP_REENVIAR_ACTIVACION
(
    @CORREO_ELECTRONICO NVARCHAR(100),
    @NUEVO_CODIGO       NVARCHAR(MAX),
    @IDRETURN           INT OUTPUT,
    @ERRORID            INT OUTPUT,
    @ERRORDESCRIPCION   NVARCHAR(MAX) OUTPUT
)
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT OFF;
    BEGIN TRY
        DECLARE @ESTADO INT;
        SELECT @ESTADO = ESTADO FROM dbo.TB_USUARIO WHERE CORREO_ELECTRONICO = @CORREO_ELECTRONICO;
        IF @ESTADO IS NULL  BEGIN SET @IDRETURN=-1; SET @ERRORID=1;  SET @ERRORDESCRIPCION=N'CORREO NO REGISTRADO';   RETURN; END
        IF @ESTADO = 1      BEGIN SET @IDRETURN=-1; SET @ERRORID=2;  SET @ERRORDESCRIPCION=N'LA CUENTA YA ESTA ACTIVA'; RETURN; END
        IF @ESTADO = 2      BEGIN SET @IDRETURN=-1; SET @ERRORID=3;  SET @ERRORDESCRIPCION=N'CUENTA DESACTIVADA';      RETURN; END
        UPDATE dbo.TB_USUARIO SET NUMERO_VERIFICACION = @NUEVO_CODIGO, FECHA_CODIGO_VERIFICACION = GETUTCDATE()
        WHERE CORREO_ELECTRONICO = @CORREO_ELECTRONICO AND ESTADO = 0;
        SET @IDRETURN = @@ROWCOUNT; SET @ERRORID = 0; SET @ERRORDESCRIPCION = N'';
    END TRY
    BEGIN CATCH
        IF XACT_STATE() <> 0 ROLLBACK;
        SET @IDRETURN = -1; SET @ERRORID = ERROR_NUMBER(); SET @ERRORDESCRIPCION = ERROR_MESSAGE();
    END CATCH
END
GO

CREATE OR ALTER PROCEDURE dbo.SP_SOLICITAR_CAMBIO_CORREO
(
    @GUID_USUARIO     UNIQUEIDENTIFIER,
    @CORREO_NUEVO     NVARCHAR(150),
    @CODIGO           NVARCHAR(100),
    @IDRETURN         INT OUTPUT,
    @ERRORID          INT OUTPUT,
    @ERRORDESCRIPCION NVARCHAR(MAX) OUTPUT
)
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT OFF;
    BEGIN TRY
        IF EXISTS (SELECT 1 FROM dbo.TB_USUARIO WHERE CORREO_ELECTRONICO = @CORREO_NUEVO AND GUID_USUARIO <> @GUID_USUARIO)
            BEGIN SET @IDRETURN=-1; SET @ERRORID=1; SET @ERRORDESCRIPCION=N'EL CORREO NUEVO YA ESTÁ EN USO'; RETURN; END
        IF NOT EXISTS (SELECT 1 FROM dbo.TB_USUARIO WHERE GUID_USUARIO = @GUID_USUARIO AND ESTADO = 1)
            BEGIN SET @IDRETURN=-1; SET @ERRORID=6; SET @ERRORDESCRIPCION=N'USUARIO NO ENCONTRADO O INACTIVO'; RETURN; END
        UPDATE dbo.TB_USUARIO
        SET CORREO_PENDIENTE = @CORREO_NUEVO, CODIGO_CAMBIO_CORREO = @CODIGO, FECHA_CODIGO_CORREO = GETDATE()
        WHERE GUID_USUARIO = @GUID_USUARIO;
        SET @IDRETURN = @@ROWCOUNT; SET @ERRORID = 0; SET @ERRORDESCRIPCION = N'';
    END TRY
    BEGIN CATCH
        IF XACT_STATE() <> 0 ROLLBACK;
        SET @IDRETURN = -1; SET @ERRORID = ERROR_NUMBER(); SET @ERRORDESCRIPCION = ERROR_MESSAGE();
    END CATCH
END
GO

CREATE OR ALTER PROCEDURE dbo.SP_CONFIRMAR_CAMBIO_CORREO
(
    @GUID_USUARIO     UNIQUEIDENTIFIER,
    @CODIGO           NVARCHAR(100),
    @IDRETURN         INT OUTPUT,
    @ERRORID          INT OUTPUT,
    @ERRORDESCRIPCION NVARCHAR(MAX) OUTPUT
)
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT OFF;
    BEGIN TRY
        DECLARE @CORREO_PENDIENTE NVARCHAR(150), @CODIGO_GUARDADO NVARCHAR(100), @FECHA_CODIGO DATETIME;
        SELECT @CORREO_PENDIENTE = CORREO_PENDIENTE, @CODIGO_GUARDADO = CODIGO_CAMBIO_CORREO, @FECHA_CODIGO = FECHA_CODIGO_CORREO
        FROM dbo.TB_USUARIO WHERE GUID_USUARIO = @GUID_USUARIO AND ESTADO = 1;
        IF @CORREO_PENDIENTE IS NULL OR @CODIGO_GUARDADO IS NULL
            BEGIN SET @IDRETURN=-1; SET @ERRORID=12; SET @ERRORDESCRIPCION=N'NO HAY SOLICITUD PENDIENTE'; RETURN; END
        IF DATEDIFF(MINUTE, @FECHA_CODIGO, GETDATE()) > 30
        BEGIN
            UPDATE dbo.TB_USUARIO SET CORREO_PENDIENTE=NULL, CODIGO_CAMBIO_CORREO=NULL, FECHA_CODIGO_CORREO=NULL WHERE GUID_USUARIO=@GUID_USUARIO;
            SET @IDRETURN=-1; SET @ERRORID=12; SET @ERRORDESCRIPCION=N'EL CÓDIGO HA EXPIRADO'; RETURN;
        END
        IF @CODIGO_GUARDADO <> @CODIGO
            BEGIN SET @IDRETURN=-1; SET @ERRORID=43; SET @ERRORDESCRIPCION=N'CÓDIGO INCORRECTO'; RETURN; END
        UPDATE dbo.TB_USUARIO
        SET CORREO_ELECTRONICO=@CORREO_PENDIENTE, CORREO_PENDIENTE=NULL, CODIGO_CAMBIO_CORREO=NULL, FECHA_CODIGO_CORREO=NULL
        WHERE GUID_USUARIO=@GUID_USUARIO;
        SET @IDRETURN = @@ROWCOUNT; SET @ERRORID = 0; SET @ERRORDESCRIPCION = N'';
    END TRY
    BEGIN CATCH
        IF XACT_STATE() <> 0 ROLLBACK;
        SET @IDRETURN = -1; SET @ERRORID = ERROR_NUMBER(); SET @ERRORDESCRIPCION = ERROR_MESSAGE();
    END CATCH
END
GO

CREATE OR ALTER PROCEDURE dbo.SP_REACTIVAR_USUARIO
(
    @CORREO_ELECTRONICO NVARCHAR(100),
    @CODIGO             NVARCHAR(100),
    @IDRETURN           INT OUTPUT,
    @ERRORID            INT OUTPUT,
    @ERRORDESCRIPCION   NVARCHAR(MAX) OUTPUT
)
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT OFF;
    BEGIN TRY
        DECLARE @ESTADO INT, @CODIGO_GUARDADO NVARCHAR(100), @FECHA_CODIGO DATETIME;
        SELECT @ESTADO=ESTADO, @CODIGO_GUARDADO=NUMERO_VERIFICACION, @FECHA_CODIGO=FECHA_CODIGO_VERIFICACION
        FROM dbo.TB_USUARIO WHERE CORREO_ELECTRONICO=@CORREO_ELECTRONICO;
        IF @ESTADO IS NULL  BEGIN SET @IDRETURN=-1; SET @ERRORID=14; SET @ERRORDESCRIPCION=N'CORREO NO REGISTRADO';          RETURN; END
        IF @ESTADO <> 2     BEGIN SET @IDRETURN=-1; SET @ERRORID=47; SET @ERRORDESCRIPCION=N'LA CUENTA NO ESTÁ DESACTIVADA'; RETURN; END
        IF @CODIGO_GUARDADO IS NULL OR @FECHA_CODIGO IS NULL
                            BEGIN SET @IDRETURN=-1; SET @ERRORID=12; SET @ERRORDESCRIPCION=N'SIN SOLICITUD PENDIENTE';        RETURN; END
        IF DATEDIFF(MINUTE, @FECHA_CODIGO, GETDATE()) > 30
        BEGIN
            UPDATE dbo.TB_USUARIO SET NUMERO_VERIFICACION=NULL, FECHA_CODIGO_VERIFICACION=NULL WHERE CORREO_ELECTRONICO=@CORREO_ELECTRONICO;
            SET @IDRETURN=-1; SET @ERRORID=12; SET @ERRORDESCRIPCION=N'EL CÓDIGO HA EXPIRADO'; RETURN;
        END
        IF @CODIGO_GUARDADO <> @CODIGO BEGIN SET @IDRETURN=-1; SET @ERRORID=45; SET @ERRORDESCRIPCION=N'CÓDIGO INCORRECTO'; RETURN; END
        UPDATE dbo.TB_USUARIO SET ESTADO=1, NUMERO_VERIFICACION=NULL, FECHA_CODIGO_VERIFICACION=NULL
        WHERE CORREO_ELECTRONICO=@CORREO_ELECTRONICO AND ESTADO=2;
        SET @IDRETURN = @@ROWCOUNT; SET @ERRORID = 0; SET @ERRORDESCRIPCION = N'';
    END TRY
    BEGIN CATCH
        IF XACT_STATE() <> 0 ROLLBACK;
        SET @IDRETURN = -1; SET @ERRORID = ERROR_NUMBER(); SET @ERRORDESCRIPCION = ERROR_MESSAGE();
    END CATCH
END
GO

CREATE OR ALTER PROCEDURE dbo.SP_SOLICITAR_REACTIVACION
(
    @CORREO_ELECTRONICO NVARCHAR(100),
    @CODIGO             NVARCHAR(100),
    @IDRETURN           INT OUTPUT,
    @ERRORID            INT OUTPUT,
    @ERRORDESCRIPCION   NVARCHAR(MAX) OUTPUT,
    @NOMBRE             NVARCHAR(100) OUTPUT,
    @APELLIDOS          NVARCHAR(150) OUTPUT
)
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT OFF;
    BEGIN TRY
        DECLARE @ESTADO INT;
        SELECT @ESTADO=ESTADO, @NOMBRE=NOMBRE, @APELLIDOS=APELLIDOS FROM dbo.TB_USUARIO WHERE CORREO_ELECTRONICO=@CORREO_ELECTRONICO;
        IF @ESTADO IS NULL BEGIN SET @IDRETURN=-1; SET @ERRORID=14; SET @ERRORDESCRIPCION=N'CORREO NO REGISTRADO';          RETURN; END
        IF @ESTADO <> 2    BEGIN SET @IDRETURN=-1; SET @ERRORID=47; SET @ERRORDESCRIPCION=N'LA CUENTA NO ESTÁ DESACTIVADA'; RETURN; END
        UPDATE dbo.TB_USUARIO SET NUMERO_VERIFICACION=@CODIGO, FECHA_CODIGO_VERIFICACION=GETDATE()
        WHERE CORREO_ELECTRONICO=@CORREO_ELECTRONICO AND ESTADO=2;
        SET @IDRETURN = @@ROWCOUNT; SET @ERRORID = 0; SET @ERRORDESCRIPCION = N'';
    END TRY
    BEGIN CATCH
        IF XACT_STATE() <> 0 ROLLBACK;
        SET @IDRETURN = -1; SET @ERRORID = ERROR_NUMBER(); SET @ERRORDESCRIPCION = ERROR_MESSAGE();
    END CATCH
END
GO

-- ============================================================
-- VERIFICACIÓN
-- SELECT TOP 10 * FROM dbo.TB_ERROR_EN_BASE_DATOS ORDER BY ID DESC;
-- ============================================================
