ALTER PROCEDURE dbo.SP_OBTENER_LISTAUSUARIOS
AS
BEGIN
    SET NOCOUNT ON;
    SELECT
        u.GUID_USUARIO,
        u.NOMBRE,
        u.APELLIDOS,
        u.CORREO_ELECTRONICO,
        u.FECHA_REGISTRO,
        u.ESTADO
    FROM dbo.TB_USUARIO u;
END
