CREATE OR ALTER PROCEDURE dbo.SP_LOGIN
(
    @CORREO_ELECTRONICO NVARCHAR(100)
)
AS
BEGIN
    SET NOCOUNT ON;
    SELECT
        u.GUID_USUARIO,
        u.NOMBRE,
        u.APELLIDOS,
        u.ESTADO,
        u.[PASSWORD] AS HASH_PASSWORD
    FROM dbo.TB_USUARIO u
    WHERE u.CORREO_ELECTRONICO = @CORREO_ELECTRONICO;
END
