-- SP_INGRESAR_USUARIO: guarda la fecha del codigo para controlar expiracion de 10 min
ALTER PROCEDURE dbo.SP_INGRESAR_USUARIO
(
    @NOMBRE              NVARCHAR(50),
    @APELLIDOS           NVARCHAR(50),
    @CORREO_ELECTRONICO  NVARCHAR(100),
    @PASSWORD            NVARCHAR(MAX),
    @NUMERO_VERIFICACION NVARCHAR(MAX),
    @GUID_USUARIO        UNIQUEIDENTIFIER OUTPUT,
    @IDRETURN            INT OUTPUT,
    @ERRORID             INT OUTPUT,
    @ERRORDESCRIPCION    NVARCHAR(MAX) OUTPUT
)
AS
BEGIN
    SET NOCOUNT ON;
    BEGIN TRY
        IF EXISTS (SELECT 1 FROM dbo.TB_USUARIO WHERE CORREO_ELECTRONICO = @CORREO_ELECTRONICO)
        BEGIN
            SET @IDRETURN        = -1;
            SET @ERRORID         = 1;
            SET @ERRORDESCRIPCION = N'ERROR: CORREO YA REGISTRADO';
            RETURN;
        END

        INSERT INTO dbo.TB_USUARIO
            (NOMBRE, APELLIDOS, CORREO_ELECTRONICO, [PASSWORD], ESTADO, FECHA_REGISTRO, NUMERO_VERIFICACION, FECHA_CODIGO_VERIFICACION)
        VALUES
            (@NOMBRE, @APELLIDOS, @CORREO_ELECTRONICO, @PASSWORD, 0, GETUTCDATE(), @NUMERO_VERIFICACION, GETUTCDATE());

        DECLARE @ID BIGINT = SCOPE_IDENTITY();
        SELECT @GUID_USUARIO = GUID_USUARIO FROM dbo.TB_USUARIO WHERE ID_USUARIO = @ID;

        SET @IDRETURN        = @ID;
        SET @ERRORID         = 0;
        SET @ERRORDESCRIPCION = N'';
    END TRY
    BEGIN CATCH
        SET @IDRETURN        = -1;
        SET @ERRORID         = ERROR_NUMBER();
        SET @ERRORDESCRIPCION = ERROR_MESSAGE();
        INSERT INTO dbo.TB_ERROR_EN_BASE_DATOS(SEVERIDAD, STORED_PROCEDURE, NUMERO, DESCRIPCION, LINEA)
        SELECT ERROR_SEVERITY(), ERROR_PROCEDURE(), ERROR_NUMBER(), ERROR_MESSAGE(), ERROR_LINE();
    END CATCH
END
