//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=KHRIZ;Initial Catalog=bdMiBus;Integrated Security=True;Connect Timeou" +
            "t=30;Encrypt=False;TrustServerCertificate=True")]
        public string bdMiBusConnectionString {
            get {
                return ((string)(this["bdMiBusConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=KHRIZ;Initial Catalog=bdMiBus;Integrated Security=True;Connect Timeou" +
            "t=30;Encrypt=False;TrustServerCertificate=True")]
        public string bdMiBusConnectionString1 {
            get {
                return ((string)(this["bdMiBusConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=KHRIZ;Initial Catalog=bdMiBus;Integrated Security=True;Connect Timeou" +
            "t=30;Encrypt=False;TrustServerCertificate=True")]
        public string bdMiBusConnectionString2 {
            get {
                return ((string)(this["bdMiBusConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=mibus.database.windows.net;Initial Catalog=bdMiBus;Persist Security I" +
            "nfo=True;User ID=mibusroot;TrustServerCertificate=True")]
        public string bdMiBusConnectionString3 {
            get {
                return ((string)(this["bdMiBusConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=mibus.database.windows.net;Initial Catalog=bdMiBus;Persist Security I" +
            "nfo=True;User ID=mibusroot;TrustServerCertificate=True")]
        public string bdMiBusConnectionString4 {
            get {
                return ((string)(this["bdMiBusConnectionString4"]));
            }
        }
    }
}
