#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="bdMiBus")]
	public partial class ConexionLinqDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTB_HISTORIAL_VIAJE(TB_HISTORIAL_VIAJE instance);
    partial void UpdateTB_HISTORIAL_VIAJE(TB_HISTORIAL_VIAJE instance);
    partial void DeleteTB_HISTORIAL_VIAJE(TB_HISTORIAL_VIAJE instance);
    #endregion
		
		public ConexionLinqDataContext() : 
				base(global::AccesoDatos.Properties.Settings.Default.bdMiBusConnectionString2, mappingSource)
		{
			OnCreated();
		}
		
		public ConexionLinqDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ConexionLinqDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ConexionLinqDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ConexionLinqDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<TB_HISTORIAL_VIAJE> TB_HISTORIAL_VIAJE
		{
			get
			{
				return this.GetTable<TB_HISTORIAL_VIAJE>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_INGRESAR_USUARIO")]
		public int SP_INGRESAR_USUARIO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="NOMBRE", DbType="NVarChar(50)")] string nOMBRE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="APELLIDOS", DbType="NVarChar(50)")] string aPELLIDOS, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CORREO_ELECTRONICO", DbType="NVarChar(100)")] string cORREO_ELECTRONICO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PASSWORD", DbType="NVarChar(MAX)")] string pASSWORD, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NUMERO_VERIFICACION", DbType="NVarChar(MAX)")] string nUMERO_VERIFICACION, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="GUID_USUARIO", DbType="UniqueIdentifier")] ref System.Nullable<System.Guid> gUID_USUARIO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nOMBRE, aPELLIDOS, cORREO_ELECTRONICO, pASSWORD, nUMERO_VERIFICACION, gUID_USUARIO, iDRETURN, eRRORID, eRRORDESCRIPCION);
			gUID_USUARIO = ((System.Nullable<System.Guid>)(result.GetParameterValue(5)));
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(6)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(7)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(8)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_OBTENER_USUARIO")]
		public ISingleResult<SP_OBTENER_USUARIOResult> SP_OBTENER_USUARIO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="GUID_USUARIO", DbType="UniqueIdentifier")] System.Nullable<System.Guid> gUID_USUARIO)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), gUID_USUARIO);
			return ((ISingleResult<SP_OBTENER_USUARIOResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_VALIDAR_SESION")]
		public ISingleResult<SP_VALIDAR_SESIONResult> SP_VALIDAR_SESION([global::System.Data.Linq.Mapping.ParameterAttribute(Name="GUID_SESION", DbType="UniqueIdentifier")] System.Nullable<System.Guid> gUID_SESION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), gUID_SESION);
			return ((ISingleResult<SP_VALIDAR_SESIONResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_REGISTRAR_HISTORIAL")]
		public int SP_REGISTRAR_HISTORIAL([global::System.Data.Linq.Mapping.ParameterAttribute(Name="GUID_USUARIO", DbType="UniqueIdentifier")] System.Nullable<System.Guid> gUID_USUARIO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="GUID_RUTA", DbType="UniqueIdentifier")] System.Nullable<System.Guid> gUID_RUTA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="GUID_HISTORIAL", DbType="UniqueIdentifier")] ref System.Nullable<System.Guid> gUID_HISTORIAL, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), gUID_USUARIO, gUID_RUTA, gUID_HISTORIAL, iDRETURN, eRRORID, eRRORDESCRIPCION);
			gUID_HISTORIAL = ((System.Nullable<System.Guid>)(result.GetParameterValue(2)));
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(3)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(4)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(5)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_OBTENER_LISTAUSUARIOS")]
		public ISingleResult<SP_OBTENER_LISTAUSUARIOSResult> SP_OBTENER_LISTAUSUARIOS()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<SP_OBTENER_LISTAUSUARIOSResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_OBTENER_HISTORIAL_POR_USUARIO")]
		public ISingleResult<SP_OBTENER_HISTORIAL_POR_USUARIOResult> SP_OBTENER_HISTORIAL_POR_USUARIO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="GUID_USUARIO", DbType="UniqueIdentifier")] System.Nullable<System.Guid> gUID_USUARIO)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), gUID_USUARIO);
			return ((ISingleResult<SP_OBTENER_HISTORIAL_POR_USUARIOResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_OBTENER_FAVORITOS_POR_USUARIO")]
		public ISingleResult<SP_OBTENER_FAVORITOS_POR_USUARIOResult> SP_OBTENER_FAVORITOS_POR_USUARIO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="GUID_USUARIO", DbType="UniqueIdentifier")] System.Nullable<System.Guid> gUID_USUARIO)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), gUID_USUARIO);
			return ((ISingleResult<SP_OBTENER_FAVORITOS_POR_USUARIOResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ELIMINAR_FAVORITO")]
		public int SP_ELIMINAR_FAVORITO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="GUID_FAVORITO", DbType="UniqueIdentifier")] System.Nullable<System.Guid> gUID_FAVORITO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), gUID_FAVORITO, iDRETURN, eRRORID, eRRORDESCRIPCION);
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(1)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(2)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(3)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_CERRAR_SESION")]
		public int SP_CERRAR_SESION([global::System.Data.Linq.Mapping.ParameterAttribute(Name="GUID_SESION", DbType="UniqueIdentifier")] System.Nullable<System.Guid> gUID_SESION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), gUID_SESION);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_AGREGAR_FAVORITO")]
		public int SP_AGREGAR_FAVORITO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="GUID_USUARIO", DbType="UniqueIdentifier")] System.Nullable<System.Guid> gUID_USUARIO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="GUID_RUTA", DbType="UniqueIdentifier")] System.Nullable<System.Guid> gUID_RUTA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="GUID_FAVORITO", DbType="UniqueIdentifier")] ref System.Nullable<System.Guid> gUID_FAVORITO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), gUID_USUARIO, gUID_RUTA, gUID_FAVORITO, iDRETURN, eRRORID, eRRORDESCRIPCION);
			gUID_FAVORITO = ((System.Nullable<System.Guid>)(result.GetParameterValue(2)));
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(3)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(4)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(5)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ABRIR_SESION")]
		public int SP_ABRIR_SESION([global::System.Data.Linq.Mapping.ParameterAttribute(Name="SESION", DbType="NVarChar(MAX)")] string sESION, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="GUID_USUARIO", DbType="UniqueIdentifier")] System.Nullable<System.Guid> gUID_USUARIO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ORIGEN", DbType="NVarChar(MAX)")] string oRIGEN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="GUID_SESION", DbType="UniqueIdentifier")] ref System.Nullable<System.Guid> gUID_SESION, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), sESION, gUID_USUARIO, oRIGEN, gUID_SESION, iDRETURN, eRRORID, eRRORDESCRIPCION);
			gUID_SESION = ((System.Nullable<System.Guid>)(result.GetParameterValue(3)));
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(4)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(5)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(6)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ACTIVAR_USUARIO")]
		public int SP_ACTIVAR_USUARIO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CORREO_ELECTRONICO", DbType="NVarChar(100)")] string cORREO_ELECTRONICO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NUMERO_VERIFICACION", DbType="NVarChar(MAX)")] string nUMERO_VERIFICACION, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FILASACTUALIZADAS", DbType="Int")] ref System.Nullable<int> fILASACTUALIZADAS, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cORREO_ELECTRONICO, nUMERO_VERIFICACION, fILASACTUALIZADAS, iDRETURN, eRRORID, eRRORDESCRIPCION);
			fILASACTUALIZADAS = ((System.Nullable<int>)(result.GetParameterValue(2)));
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(3)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(4)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(5)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_INSERTAR_BITACORA")]
		public int SP_INSERTAR_BITACORA([global::System.Data.Linq.Mapping.ParameterAttribute(Name="GUID_USUARIO", DbType="UniqueIdentifier")] System.Nullable<System.Guid> gUID_USUARIO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CLASE", DbType="NVarChar(100)")] string cLASE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="METODO", DbType="NVarChar(100)")] string mETODO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TIPO", DbType="SmallInt")] System.Nullable<short> tIPO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CODIGO_ERROR", DbType="Int")] System.Nullable<int> cODIGO_ERROR, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DESCRIPCION", DbType="NVarChar(MAX)")] string dESCRIPCION, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="REQUEST", DbType="NVarChar(MAX)")] string rEQUEST, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="RESPONSE", DbType="NVarChar(MAX)")] string rESPONSE)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), gUID_USUARIO, cLASE, mETODO, tIPO, cODIGO_ERROR, dESCRIPCION, rEQUEST, rESPONSE);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ELIMINAR_USUARIO")]
		public int SP_ELIMINAR_USUARIO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="GUID_USUARIO", DbType="UniqueIdentifier")] System.Nullable<System.Guid> gUID_USUARIO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), gUID_USUARIO, iDRETURN, eRRORID, eRRORDESCRIPCION);
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(1)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(2)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(3)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_DESACTIVAR_USUARIO")]
		public int SP_DESACTIVAR_USUARIO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="GUID_USUARIO", DbType="UniqueIdentifier")] System.Nullable<System.Guid> gUID_USUARIO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), gUID_USUARIO, iDRETURN, eRRORID, eRRORDESCRIPCION);
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(1)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(2)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(3)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ACTUALIZAR_USUARIO")]
		public int SP_ACTUALIZAR_USUARIO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="GUID_USUARIO", DbType="UniqueIdentifier")] System.Nullable<System.Guid> gUID_USUARIO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NOMBRE", DbType="NVarChar(50)")] string nOMBRE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="APELLIDOS", DbType="NVarChar(50)")] string aPELLIDOS, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), gUID_USUARIO, nOMBRE, aPELLIDOS, iDRETURN, eRRORID, eRRORDESCRIPCION);
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(3)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(4)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(5)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_OBTENER_PARADA_POR_GUID")]
		public ISingleResult<SP_OBTENER_PARADA_POR_GUIDResult> SP_OBTENER_PARADA_POR_GUID([global::System.Data.Linq.Mapping.ParameterAttribute(Name="GUID_PARADA", DbType="UniqueIdentifier")] System.Nullable<System.Guid> gUID_PARADA)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), gUID_PARADA);
			return ((ISingleResult<SP_OBTENER_PARADA_POR_GUIDResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_OBTENER_PARADAS_POR_RUTA")]
		public ISingleResult<SP_OBTENER_PARADAS_POR_RUTAResult> SP_OBTENER_PARADAS_POR_RUTA([global::System.Data.Linq.Mapping.ParameterAttribute(Name="GUID_RUTA", DbType="UniqueIdentifier")] System.Nullable<System.Guid> gUID_RUTA)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), gUID_RUTA);
			return ((ISingleResult<SP_OBTENER_PARADAS_POR_RUTAResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ACTUALIZAR_RUTA")]
		public int SP_ACTUALIZAR_RUTA([global::System.Data.Linq.Mapping.ParameterAttribute(Name="GUID_RUTA", DbType="UniqueIdentifier")] System.Nullable<System.Guid> gUID_RUTA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NOMBRE", DbType="NVarChar(200)")] string nOMBRE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NUMERO_RUTA", DbType="NVarChar(20)")] string nUMERO_RUTA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="HORA_INICIO", DbType="Time")] System.Nullable<System.TimeSpan> hORA_INICIO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="HORA_FIN", DbType="Time")] System.Nullable<System.TimeSpan> hORA_FIN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ESTADO_SERVICIO", DbType="TinyInt")] System.Nullable<byte> eSTADO_SERVICIO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), gUID_RUTA, nOMBRE, nUMERO_RUTA, hORA_INICIO, hORA_FIN, eSTADO_SERVICIO, iDRETURN, eRRORID, eRRORDESCRIPCION);
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(6)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(7)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(8)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_INGRESAR_EMPRESA")]
		public int SP_INGRESAR_EMPRESA([global::System.Data.Linq.Mapping.ParameterAttribute(Name="NOMBRE", DbType="NVarChar(150)")] string nOMBRE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TELEFONO", DbType="NVarChar(20)")] string tELEFONO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CORREO", DbType="NVarChar(100)")] string cORREO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="GUID_EMPRESA", DbType="UniqueIdentifier")] ref System.Nullable<System.Guid> gUID_EMPRESA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nOMBRE, tELEFONO, cORREO, gUID_EMPRESA, iDRETURN, eRRORID, eRRORDESCRIPCION);
			gUID_EMPRESA = ((System.Nullable<System.Guid>)(result.GetParameterValue(3)));
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(4)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(5)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(6)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_OBTENER_EMPRESAS")]
		public ISingleResult<SP_OBTENER_EMPRESASResult> SP_OBTENER_EMPRESAS()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<SP_OBTENER_EMPRESASResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_INGRESAR_ZONA")]
		public int SP_INGRESAR_ZONA([global::System.Data.Linq.Mapping.ParameterAttribute(Name="NOMBRE", DbType="NVarChar(100)")] string nOMBRE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DESCRIPCION", DbType="NVarChar(MAX)")] string dESCRIPCION, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="GUID_ZONA", DbType="UniqueIdentifier")] ref System.Nullable<System.Guid> gUID_ZONA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nOMBRE, dESCRIPCION, gUID_ZONA, iDRETURN, eRRORID, eRRORDESCRIPCION);
			gUID_ZONA = ((System.Nullable<System.Guid>)(result.GetParameterValue(2)));
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(3)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(4)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(5)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_OBTENER_ZONAS")]
		public ISingleResult<SP_OBTENER_ZONASResult> SP_OBTENER_ZONAS()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<SP_OBTENER_ZONASResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_INGRESAR_TARIFA")]
		public int SP_INGRESAR_TARIFA([global::System.Data.Linq.Mapping.ParameterAttribute(Name="GUID_RUTA", DbType="UniqueIdentifier")] System.Nullable<System.Guid> gUID_RUTA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MONTO", DbType="Decimal(10,2)")] System.Nullable<decimal> mONTO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FECHA_VIGENCIA", DbType="DateTime")] System.Nullable<System.DateTime> fECHA_VIGENCIA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="GUID_TARIFA", DbType="UniqueIdentifier")] ref System.Nullable<System.Guid> gUID_TARIFA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), gUID_RUTA, mONTO, fECHA_VIGENCIA, gUID_TARIFA, iDRETURN, eRRORID, eRRORDESCRIPCION);
			gUID_TARIFA = ((System.Nullable<System.Guid>)(result.GetParameterValue(3)));
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(4)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(5)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(6)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_INGRESAR_RUTA")]
		public int SP_INGRESAR_RUTA([global::System.Data.Linq.Mapping.ParameterAttribute(Name="GUID_EMPRESA", DbType="UniqueIdentifier")] System.Nullable<System.Guid> gUID_EMPRESA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="GUID_ZONA", DbType="UniqueIdentifier")] System.Nullable<System.Guid> gUID_ZONA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NUMERO_RUTA", DbType="NVarChar(20)")] string nUMERO_RUTA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NOMBRE", DbType="NVarChar(200)")] string nOMBRE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="HORA_INICIO", DbType="Time")] System.Nullable<System.TimeSpan> hORA_INICIO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="HORA_FIN", DbType="Time")] System.Nullable<System.TimeSpan> hORA_FIN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ESTADO_SERVICIO", DbType="TinyInt")] System.Nullable<byte> eSTADO_SERVICIO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="GUID_RUTA", DbType="UniqueIdentifier")] ref System.Nullable<System.Guid> gUID_RUTA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), gUID_EMPRESA, gUID_ZONA, nUMERO_RUTA, nOMBRE, hORA_INICIO, hORA_FIN, eSTADO_SERVICIO, gUID_RUTA, iDRETURN, eRRORID, eRRORDESCRIPCION);
			gUID_RUTA = ((System.Nullable<System.Guid>)(result.GetParameterValue(7)));
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(8)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(9)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(10)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ACTUALIZAR_RUTA")]
		public int SP_ACTUALIZAR_RUTA1([global::System.Data.Linq.Mapping.ParameterAttribute(Name="GUID_RUTA", DbType="UniqueIdentifier")] System.Nullable<System.Guid> gUID_RUTA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NOMBRE", DbType="NVarChar(200)")] string nOMBRE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NUMERO_RUTA", DbType="NVarChar(20)")] string nUMERO_RUTA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="HORA_INICIO", DbType="Time")] System.Nullable<System.TimeSpan> hORA_INICIO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="HORA_FIN", DbType="Time")] System.Nullable<System.TimeSpan> hORA_FIN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ESTADO_SERVICIO", DbType="TinyInt")] System.Nullable<byte> eSTADO_SERVICIO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), gUID_RUTA, nOMBRE, nUMERO_RUTA, hORA_INICIO, hORA_FIN, eSTADO_SERVICIO, iDRETURN, eRRORID, eRRORDESCRIPCION);
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(6)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(7)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(8)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_OBTENER_RUTAS")]
		public ISingleResult<SP_OBTENER_RUTASResult> SP_OBTENER_RUTAS([global::System.Data.Linq.Mapping.ParameterAttribute(Name="SOLO_ACTIVAS", DbType="Bit")] System.Nullable<bool> sOLO_ACTIVAS)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), sOLO_ACTIVAS);
			return ((ISingleResult<SP_OBTENER_RUTASResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_OBTENER_RUTA_POR_GUID")]
		public ISingleResult<SP_OBTENER_RUTA_POR_GUIDResult> SP_OBTENER_RUTA_POR_GUID([global::System.Data.Linq.Mapping.ParameterAttribute(Name="GUID_RUTA", DbType="UniqueIdentifier")] System.Nullable<System.Guid> gUID_RUTA)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), gUID_RUTA);
			return ((ISingleResult<SP_OBTENER_RUTA_POR_GUIDResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_DESACTIVAR_RUTA")]
		public int SP_DESACTIVAR_RUTA([global::System.Data.Linq.Mapping.ParameterAttribute(Name="GUID_RUTA", DbType="UniqueIdentifier")] System.Nullable<System.Guid> gUID_RUTA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), gUID_RUTA, iDRETURN, eRRORID, eRRORDESCRIPCION);
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(1)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(2)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(3)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ASOCIAR_PARADA_RUTA")]
		public int SP_ASOCIAR_PARADA_RUTA([global::System.Data.Linq.Mapping.ParameterAttribute(Name="GUID_RUTA", DbType="UniqueIdentifier")] System.Nullable<System.Guid> gUID_RUTA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="GUID_PARADA", DbType="UniqueIdentifier")] System.Nullable<System.Guid> gUID_PARADA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ORDEN", DbType="Int")] System.Nullable<int> oRDEN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="GUID_RUTA_PARADA", DbType="UniqueIdentifier")] ref System.Nullable<System.Guid> gUID_RUTA_PARADA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), gUID_RUTA, gUID_PARADA, oRDEN, gUID_RUTA_PARADA, iDRETURN, eRRORID, eRRORDESCRIPCION);
			gUID_RUTA_PARADA = ((System.Nullable<System.Guid>)(result.GetParameterValue(3)));
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(4)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(5)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(6)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_INGRESAR_HORARIO")]
		public int SP_INGRESAR_HORARIO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="GUID_RUTA", DbType="UniqueIdentifier")] System.Nullable<System.Guid> gUID_RUTA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="HORA_SALIDA", DbType="Time")] System.Nullable<System.TimeSpan> hORA_SALIDA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DIAS_SERVICIO", DbType="TinyInt")] System.Nullable<byte> dIAS_SERVICIO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="GUID_HORARIO", DbType="UniqueIdentifier")] ref System.Nullable<System.Guid> gUID_HORARIO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), gUID_RUTA, hORA_SALIDA, dIAS_SERVICIO, gUID_HORARIO, iDRETURN, eRRORID, eRRORDESCRIPCION);
			gUID_HORARIO = ((System.Nullable<System.Guid>)(result.GetParameterValue(3)));
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(4)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(5)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(6)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_OBTENER_HORARIOS_POR_RUTA")]
		public ISingleResult<SP_OBTENER_HORARIOS_POR_RUTAResult> SP_OBTENER_HORARIOS_POR_RUTA([global::System.Data.Linq.Mapping.ParameterAttribute(Name="GUID_RUTA", DbType="UniqueIdentifier")] System.Nullable<System.Guid> gUID_RUTA)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), gUID_RUTA);
			return ((ISingleResult<SP_OBTENER_HORARIOS_POR_RUTAResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_LOGIN")]
		public ISingleResult<SP_LOGINResult> SP_LOGIN([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CORREO_ELECTRONICO", DbType="NVarChar(100)")] string cORREO_ELECTRONICO)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cORREO_ELECTRONICO);
			return ((ISingleResult<SP_LOGINResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ACTUALIZAR_EMPRESA")]
		public int SP_ACTUALIZAR_EMPRESA([global::System.Data.Linq.Mapping.ParameterAttribute(Name="GUID_EMPRESA", DbType="UniqueIdentifier")] System.Nullable<System.Guid> gUID_EMPRESA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NOMBRE", DbType="NVarChar(150)")] string nOMBRE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TELEFONO", DbType="NVarChar(20)")] string tELEFONO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CORREO", DbType="NVarChar(100)")] string cORREO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), gUID_EMPRESA, nOMBRE, tELEFONO, cORREO, iDRETURN, eRRORID, eRRORDESCRIPCION);
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(4)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(5)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(6)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ELIMINAR_EMPRESA")]
		public int SP_ELIMINAR_EMPRESA([global::System.Data.Linq.Mapping.ParameterAttribute(Name="GUID_EMPRESA", DbType="UniqueIdentifier")] System.Nullable<System.Guid> gUID_EMPRESA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), gUID_EMPRESA, iDRETURN, eRRORID, eRRORDESCRIPCION);
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(1)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(2)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(3)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ACTUALIZAR_ZONA")]
		public int SP_ACTUALIZAR_ZONA([global::System.Data.Linq.Mapping.ParameterAttribute(Name="GUID_ZONA", DbType="UniqueIdentifier")] System.Nullable<System.Guid> gUID_ZONA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NOMBRE", DbType="NVarChar(100)")] string nOMBRE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DESCRIPCION", DbType="NVarChar(MAX)")] string dESCRIPCION, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), gUID_ZONA, nOMBRE, dESCRIPCION, iDRETURN, eRRORID, eRRORDESCRIPCION);
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(3)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(4)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(5)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ELIMINAR_ZONA")]
		public int SP_ELIMINAR_ZONA([global::System.Data.Linq.Mapping.ParameterAttribute(Name="GUID_ZONA", DbType="UniqueIdentifier")] System.Nullable<System.Guid> gUID_ZONA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), gUID_ZONA, iDRETURN, eRRORID, eRRORDESCRIPCION);
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(1)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(2)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(3)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_OBTENER_TARIFAS_POR_RUTA")]
		public ISingleResult<SP_OBTENER_TARIFAS_POR_RUTAResult> SP_OBTENER_TARIFAS_POR_RUTA([global::System.Data.Linq.Mapping.ParameterAttribute(Name="GUID_RUTA", DbType="UniqueIdentifier")] System.Nullable<System.Guid> gUID_RUTA)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), gUID_RUTA);
			return ((ISingleResult<SP_OBTENER_TARIFAS_POR_RUTAResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_OBTENER_TARIFA_POR_GUID")]
		public ISingleResult<SP_OBTENER_TARIFA_POR_GUIDResult> SP_OBTENER_TARIFA_POR_GUID([global::System.Data.Linq.Mapping.ParameterAttribute(Name="GUID_TARIFA", DbType="UniqueIdentifier")] System.Nullable<System.Guid> gUID_TARIFA)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), gUID_TARIFA);
			return ((ISingleResult<SP_OBTENER_TARIFA_POR_GUIDResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ACTUALIZAR_TARIFA")]
		public int SP_ACTUALIZAR_TARIFA([global::System.Data.Linq.Mapping.ParameterAttribute(Name="GUID_TARIFA", DbType="UniqueIdentifier")] System.Nullable<System.Guid> gUID_TARIFA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MONTO", DbType="Decimal(10,2)")] System.Nullable<decimal> mONTO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FECHA_VIGENCIA", DbType="DateTime")] System.Nullable<System.DateTime> fECHA_VIGENCIA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), gUID_TARIFA, mONTO, fECHA_VIGENCIA, iDRETURN, eRRORID, eRRORDESCRIPCION);
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(3)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(4)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(5)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ELIMINAR_TARIFA")]
		public int SP_ELIMINAR_TARIFA([global::System.Data.Linq.Mapping.ParameterAttribute(Name="GUID_TARIFA", DbType="UniqueIdentifier")] System.Nullable<System.Guid> gUID_TARIFA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), gUID_TARIFA, iDRETURN, eRRORID, eRRORDESCRIPCION);
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(1)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(2)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(3)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_OBTENER_HORARIO_POR_GUID")]
		public ISingleResult<SP_OBTENER_HORARIO_POR_GUIDResult> SP_OBTENER_HORARIO_POR_GUID([global::System.Data.Linq.Mapping.ParameterAttribute(Name="GUID_HORARIO", DbType="UniqueIdentifier")] System.Nullable<System.Guid> gUID_HORARIO)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), gUID_HORARIO);
			return ((ISingleResult<SP_OBTENER_HORARIO_POR_GUIDResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ACTUALIZAR_HORARIO")]
		public int SP_ACTUALIZAR_HORARIO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="GUID_HORARIO", DbType="UniqueIdentifier")] System.Nullable<System.Guid> gUID_HORARIO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="HORA_SALIDA", DbType="Time")] System.Nullable<System.TimeSpan> hORA_SALIDA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DIAS_SERVICIO", DbType="TinyInt")] System.Nullable<byte> dIAS_SERVICIO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), gUID_HORARIO, hORA_SALIDA, dIAS_SERVICIO, iDRETURN, eRRORID, eRRORDESCRIPCION);
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(3)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(4)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(5)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ELIMINAR_HORARIO")]
		public int SP_ELIMINAR_HORARIO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="GUID_HORARIO", DbType="UniqueIdentifier")] System.Nullable<System.Guid> gUID_HORARIO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), gUID_HORARIO, iDRETURN, eRRORID, eRRORDESCRIPCION);
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(1)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(2)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(3)));
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TB_HISTORIAL_VIAJE")]
	public partial class TB_HISTORIAL_VIAJE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_HISTORIAL;
		
		private System.Guid _GUID_HISTORIAL;
		
		private long _ID_USUARIO;
		
		private int _ID_RUTA;
		
		private System.Nullable<int> _ID_TARIFA;
		
		private System.DateTime _FECHA_CONSULTA;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_HISTORIALChanging(int value);
    partial void OnID_HISTORIALChanged();
    partial void OnGUID_HISTORIALChanging(System.Guid value);
    partial void OnGUID_HISTORIALChanged();
    partial void OnID_USUARIOChanging(long value);
    partial void OnID_USUARIOChanged();
    partial void OnID_RUTAChanging(int value);
    partial void OnID_RUTAChanged();
    partial void OnID_TARIFAChanging(System.Nullable<int> value);
    partial void OnID_TARIFAChanged();
    partial void OnFECHA_CONSULTAChanging(System.DateTime value);
    partial void OnFECHA_CONSULTAChanged();
    #endregion
		
		public TB_HISTORIAL_VIAJE()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_HISTORIAL", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_HISTORIAL
		{
			get
			{
				return this._ID_HISTORIAL;
			}
			set
			{
				if ((this._ID_HISTORIAL != value))
				{
					this.OnID_HISTORIALChanging(value);
					this.SendPropertyChanging();
					this._ID_HISTORIAL = value;
					this.SendPropertyChanged("ID_HISTORIAL");
					this.OnID_HISTORIALChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GUID_HISTORIAL", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid GUID_HISTORIAL
		{
			get
			{
				return this._GUID_HISTORIAL;
			}
			set
			{
				if ((this._GUID_HISTORIAL != value))
				{
					this.OnGUID_HISTORIALChanging(value);
					this.SendPropertyChanging();
					this._GUID_HISTORIAL = value;
					this.SendPropertyChanged("GUID_HISTORIAL");
					this.OnGUID_HISTORIALChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_USUARIO", DbType="BigInt NOT NULL")]
		public long ID_USUARIO
		{
			get
			{
				return this._ID_USUARIO;
			}
			set
			{
				if ((this._ID_USUARIO != value))
				{
					this.OnID_USUARIOChanging(value);
					this.SendPropertyChanging();
					this._ID_USUARIO = value;
					this.SendPropertyChanged("ID_USUARIO");
					this.OnID_USUARIOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_RUTA", DbType="Int NOT NULL")]
		public int ID_RUTA
		{
			get
			{
				return this._ID_RUTA;
			}
			set
			{
				if ((this._ID_RUTA != value))
				{
					this.OnID_RUTAChanging(value);
					this.SendPropertyChanging();
					this._ID_RUTA = value;
					this.SendPropertyChanged("ID_RUTA");
					this.OnID_RUTAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_TARIFA", DbType="Int")]
		public System.Nullable<int> ID_TARIFA
		{
			get
			{
				return this._ID_TARIFA;
			}
			set
			{
				if ((this._ID_TARIFA != value))
				{
					this.OnID_TARIFAChanging(value);
					this.SendPropertyChanging();
					this._ID_TARIFA = value;
					this.SendPropertyChanged("ID_TARIFA");
					this.OnID_TARIFAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA_CONSULTA", DbType="DateTime NOT NULL")]
		public System.DateTime FECHA_CONSULTA
		{
			get
			{
				return this._FECHA_CONSULTA;
			}
			set
			{
				if ((this._FECHA_CONSULTA != value))
				{
					this.OnFECHA_CONSULTAChanging(value);
					this.SendPropertyChanging();
					this._FECHA_CONSULTA = value;
					this.SendPropertyChanged("FECHA_CONSULTA");
					this.OnFECHA_CONSULTAChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class SP_OBTENER_USUARIOResult
	{
		
		private System.Guid _GUID_USUARIO;
		
		private string _NOMBRE;
		
		private string _APELLIDOS;
		
		private string _CORREO_ELECTRONICO;
		
		private System.DateTime _FECHA_REGISTRO;
		
		private System.Nullable<int> _ESTADO;
		
		public SP_OBTENER_USUARIOResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GUID_USUARIO", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid GUID_USUARIO
		{
			get
			{
				return this._GUID_USUARIO;
			}
			set
			{
				if ((this._GUID_USUARIO != value))
				{
					this._GUID_USUARIO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string NOMBRE
		{
			get
			{
				return this._NOMBRE;
			}
			set
			{
				if ((this._NOMBRE != value))
				{
					this._NOMBRE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_APELLIDOS", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string APELLIDOS
		{
			get
			{
				return this._APELLIDOS;
			}
			set
			{
				if ((this._APELLIDOS != value))
				{
					this._APELLIDOS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CORREO_ELECTRONICO", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string CORREO_ELECTRONICO
		{
			get
			{
				return this._CORREO_ELECTRONICO;
			}
			set
			{
				if ((this._CORREO_ELECTRONICO != value))
				{
					this._CORREO_ELECTRONICO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA_REGISTRO", DbType="DateTime NOT NULL")]
		public System.DateTime FECHA_REGISTRO
		{
			get
			{
				return this._FECHA_REGISTRO;
			}
			set
			{
				if ((this._FECHA_REGISTRO != value))
				{
					this._FECHA_REGISTRO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ESTADO", DbType="Int")]
		public System.Nullable<int> ESTADO
		{
			get
			{
				return this._ESTADO;
			}
			set
			{
				if ((this._ESTADO != value))
				{
					this._ESTADO = value;
				}
			}
		}
	}
	
	public partial class SP_VALIDAR_SESIONResult
	{
		
		private System.Guid _GUID_SESION;
		
		private System.Guid _GUID_USUARIO;
		
		private string _NOMBRE;
		
		private string _APELLIDOS;
		
		private bool _ESTADO;
		
		public SP_VALIDAR_SESIONResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GUID_SESION", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid GUID_SESION
		{
			get
			{
				return this._GUID_SESION;
			}
			set
			{
				if ((this._GUID_SESION != value))
				{
					this._GUID_SESION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GUID_USUARIO", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid GUID_USUARIO
		{
			get
			{
				return this._GUID_USUARIO;
			}
			set
			{
				if ((this._GUID_USUARIO != value))
				{
					this._GUID_USUARIO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string NOMBRE
		{
			get
			{
				return this._NOMBRE;
			}
			set
			{
				if ((this._NOMBRE != value))
				{
					this._NOMBRE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_APELLIDOS", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string APELLIDOS
		{
			get
			{
				return this._APELLIDOS;
			}
			set
			{
				if ((this._APELLIDOS != value))
				{
					this._APELLIDOS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ESTADO", DbType="Bit NOT NULL")]
		public bool ESTADO
		{
			get
			{
				return this._ESTADO;
			}
			set
			{
				if ((this._ESTADO != value))
				{
					this._ESTADO = value;
				}
			}
		}
	}
	
	public partial class SP_OBTENER_LISTAUSUARIOSResult
	{
		
		private System.Guid _GUID_USUARIO;
		
		private string _NOMBRE;
		
		private string _APELLIDOS;
		
		private string _CORREO_ELECTRONICO;
		
		private System.DateTime _FECHA_REGISTRO;
		
		public SP_OBTENER_LISTAUSUARIOSResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GUID_USUARIO", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid GUID_USUARIO
		{
			get
			{
				return this._GUID_USUARIO;
			}
			set
			{
				if ((this._GUID_USUARIO != value))
				{
					this._GUID_USUARIO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string NOMBRE
		{
			get
			{
				return this._NOMBRE;
			}
			set
			{
				if ((this._NOMBRE != value))
				{
					this._NOMBRE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_APELLIDOS", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string APELLIDOS
		{
			get
			{
				return this._APELLIDOS;
			}
			set
			{
				if ((this._APELLIDOS != value))
				{
					this._APELLIDOS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CORREO_ELECTRONICO", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string CORREO_ELECTRONICO
		{
			get
			{
				return this._CORREO_ELECTRONICO;
			}
			set
			{
				if ((this._CORREO_ELECTRONICO != value))
				{
					this._CORREO_ELECTRONICO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA_REGISTRO", DbType="DateTime NOT NULL")]
		public System.DateTime FECHA_REGISTRO
		{
			get
			{
				return this._FECHA_REGISTRO;
			}
			set
			{
				if ((this._FECHA_REGISTRO != value))
				{
					this._FECHA_REGISTRO = value;
				}
			}
		}
	}
	
	public partial class SP_OBTENER_HISTORIAL_POR_USUARIOResult
	{
		
		private System.Guid _GUID_HISTORIAL;
		
		private System.Guid _GUID_RUTA;
		
		private string _NOMBRE_RUTA;
		
		private System.Nullable<decimal> _TARIFA_CONSULTADA;
		
		private System.DateTime _FECHA_CONSULTA;
		
		public SP_OBTENER_HISTORIAL_POR_USUARIOResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GUID_HISTORIAL", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid GUID_HISTORIAL
		{
			get
			{
				return this._GUID_HISTORIAL;
			}
			set
			{
				if ((this._GUID_HISTORIAL != value))
				{
					this._GUID_HISTORIAL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GUID_RUTA", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid GUID_RUTA
		{
			get
			{
				return this._GUID_RUTA;
			}
			set
			{
				if ((this._GUID_RUTA != value))
				{
					this._GUID_RUTA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE_RUTA", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string NOMBRE_RUTA
		{
			get
			{
				return this._NOMBRE_RUTA;
			}
			set
			{
				if ((this._NOMBRE_RUTA != value))
				{
					this._NOMBRE_RUTA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TARIFA_CONSULTADA", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> TARIFA_CONSULTADA
		{
			get
			{
				return this._TARIFA_CONSULTADA;
			}
			set
			{
				if ((this._TARIFA_CONSULTADA != value))
				{
					this._TARIFA_CONSULTADA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA_CONSULTA", DbType="DateTime NOT NULL")]
		public System.DateTime FECHA_CONSULTA
		{
			get
			{
				return this._FECHA_CONSULTA;
			}
			set
			{
				if ((this._FECHA_CONSULTA != value))
				{
					this._FECHA_CONSULTA = value;
				}
			}
		}
	}
	
	public partial class SP_OBTENER_FAVORITOS_POR_USUARIOResult
	{
		
		private System.Guid _GUID_FAVORITO;
		
		private System.Guid _GUID_RUTA;
		
		private string _NOMBRE_RUTA;
		
		private System.Nullable<decimal> _TARIFA_ACTUAL;
		
		private System.DateTime _FECHA_REGISTRO;
		
		public SP_OBTENER_FAVORITOS_POR_USUARIOResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GUID_FAVORITO", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid GUID_FAVORITO
		{
			get
			{
				return this._GUID_FAVORITO;
			}
			set
			{
				if ((this._GUID_FAVORITO != value))
				{
					this._GUID_FAVORITO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GUID_RUTA", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid GUID_RUTA
		{
			get
			{
				return this._GUID_RUTA;
			}
			set
			{
				if ((this._GUID_RUTA != value))
				{
					this._GUID_RUTA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE_RUTA", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string NOMBRE_RUTA
		{
			get
			{
				return this._NOMBRE_RUTA;
			}
			set
			{
				if ((this._NOMBRE_RUTA != value))
				{
					this._NOMBRE_RUTA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TARIFA_ACTUAL", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> TARIFA_ACTUAL
		{
			get
			{
				return this._TARIFA_ACTUAL;
			}
			set
			{
				if ((this._TARIFA_ACTUAL != value))
				{
					this._TARIFA_ACTUAL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA_REGISTRO", DbType="DateTime NOT NULL")]
		public System.DateTime FECHA_REGISTRO
		{
			get
			{
				return this._FECHA_REGISTRO;
			}
			set
			{
				if ((this._FECHA_REGISTRO != value))
				{
					this._FECHA_REGISTRO = value;
				}
			}
		}
	}
	
	public partial class SP_OBTENER_PARADA_POR_GUIDResult
	{
		
		private System.Guid _GUID_PARADA;
		
		private string _NOMBRE;
		
		private string _DESCRIPCION;
		
		private System.Nullable<decimal> _LATITUD;
		
		private System.Nullable<decimal> _LONGITUD;
		
		private bool _ESTADO;
		
		private System.DateTime _FECHA_REGISTRO;
		
		public SP_OBTENER_PARADA_POR_GUIDResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GUID_PARADA", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid GUID_PARADA
		{
			get
			{
				return this._GUID_PARADA;
			}
			set
			{
				if ((this._GUID_PARADA != value))
				{
					this._GUID_PARADA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string NOMBRE
		{
			get
			{
				return this._NOMBRE;
			}
			set
			{
				if ((this._NOMBRE != value))
				{
					this._NOMBRE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DESCRIPCION", DbType="NVarChar(MAX)")]
		public string DESCRIPCION
		{
			get
			{
				return this._DESCRIPCION;
			}
			set
			{
				if ((this._DESCRIPCION != value))
				{
					this._DESCRIPCION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LATITUD", DbType="Decimal(10,7)")]
		public System.Nullable<decimal> LATITUD
		{
			get
			{
				return this._LATITUD;
			}
			set
			{
				if ((this._LATITUD != value))
				{
					this._LATITUD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LONGITUD", DbType="Decimal(10,7)")]
		public System.Nullable<decimal> LONGITUD
		{
			get
			{
				return this._LONGITUD;
			}
			set
			{
				if ((this._LONGITUD != value))
				{
					this._LONGITUD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ESTADO", DbType="Bit NOT NULL")]
		public bool ESTADO
		{
			get
			{
				return this._ESTADO;
			}
			set
			{
				if ((this._ESTADO != value))
				{
					this._ESTADO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA_REGISTRO", DbType="DateTime NOT NULL")]
		public System.DateTime FECHA_REGISTRO
		{
			get
			{
				return this._FECHA_REGISTRO;
			}
			set
			{
				if ((this._FECHA_REGISTRO != value))
				{
					this._FECHA_REGISTRO = value;
				}
			}
		}
	}
	
	public partial class SP_OBTENER_PARADAS_POR_RUTAResult
	{
		
		private System.Guid _GUID_PARADA;
		
		private string _NOMBRE;
		
		private string _DESCRIPCION;
		
		private System.Nullable<decimal> _LATITUD;
		
		private System.Nullable<decimal> _LONGITUD;
		
		private int _ORDEN;
		
		public SP_OBTENER_PARADAS_POR_RUTAResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GUID_PARADA", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid GUID_PARADA
		{
			get
			{
				return this._GUID_PARADA;
			}
			set
			{
				if ((this._GUID_PARADA != value))
				{
					this._GUID_PARADA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string NOMBRE
		{
			get
			{
				return this._NOMBRE;
			}
			set
			{
				if ((this._NOMBRE != value))
				{
					this._NOMBRE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DESCRIPCION", DbType="NVarChar(MAX)")]
		public string DESCRIPCION
		{
			get
			{
				return this._DESCRIPCION;
			}
			set
			{
				if ((this._DESCRIPCION != value))
				{
					this._DESCRIPCION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LATITUD", DbType="Decimal(10,7)")]
		public System.Nullable<decimal> LATITUD
		{
			get
			{
				return this._LATITUD;
			}
			set
			{
				if ((this._LATITUD != value))
				{
					this._LATITUD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LONGITUD", DbType="Decimal(10,7)")]
		public System.Nullable<decimal> LONGITUD
		{
			get
			{
				return this._LONGITUD;
			}
			set
			{
				if ((this._LONGITUD != value))
				{
					this._LONGITUD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ORDEN", DbType="Int NOT NULL")]
		public int ORDEN
		{
			get
			{
				return this._ORDEN;
			}
			set
			{
				if ((this._ORDEN != value))
				{
					this._ORDEN = value;
				}
			}
		}
	}
	
	public partial class SP_OBTENER_EMPRESASResult
	{
		
		private System.Guid _GUID_EMPRESA;
		
		private string _NOMBRE;
		
		private string _TELEFONO;
		
		private string _CORREO;
		
		private bool _ESTADO;
		
		private System.DateTime _FECHA_REGISTRO;
		
		public SP_OBTENER_EMPRESASResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GUID_EMPRESA", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid GUID_EMPRESA
		{
			get
			{
				return this._GUID_EMPRESA;
			}
			set
			{
				if ((this._GUID_EMPRESA != value))
				{
					this._GUID_EMPRESA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string NOMBRE
		{
			get
			{
				return this._NOMBRE;
			}
			set
			{
				if ((this._NOMBRE != value))
				{
					this._NOMBRE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TELEFONO", DbType="NVarChar(20)")]
		public string TELEFONO
		{
			get
			{
				return this._TELEFONO;
			}
			set
			{
				if ((this._TELEFONO != value))
				{
					this._TELEFONO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CORREO", DbType="NVarChar(100)")]
		public string CORREO
		{
			get
			{
				return this._CORREO;
			}
			set
			{
				if ((this._CORREO != value))
				{
					this._CORREO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ESTADO", DbType="Bit NOT NULL")]
		public bool ESTADO
		{
			get
			{
				return this._ESTADO;
			}
			set
			{
				if ((this._ESTADO != value))
				{
					this._ESTADO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA_REGISTRO", DbType="DateTime NOT NULL")]
		public System.DateTime FECHA_REGISTRO
		{
			get
			{
				return this._FECHA_REGISTRO;
			}
			set
			{
				if ((this._FECHA_REGISTRO != value))
				{
					this._FECHA_REGISTRO = value;
				}
			}
		}
	}
	
	public partial class SP_OBTENER_ZONASResult
	{
		
		private System.Guid _GUID_ZONA;
		
		private string _NOMBRE;
		
		private string _DESCRIPCION;
		
		private bool _ESTADO;
		
		private System.DateTime _FECHA_REGISTRO;
		
		public SP_OBTENER_ZONASResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GUID_ZONA", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid GUID_ZONA
		{
			get
			{
				return this._GUID_ZONA;
			}
			set
			{
				if ((this._GUID_ZONA != value))
				{
					this._GUID_ZONA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string NOMBRE
		{
			get
			{
				return this._NOMBRE;
			}
			set
			{
				if ((this._NOMBRE != value))
				{
					this._NOMBRE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DESCRIPCION", DbType="NVarChar(MAX)")]
		public string DESCRIPCION
		{
			get
			{
				return this._DESCRIPCION;
			}
			set
			{
				if ((this._DESCRIPCION != value))
				{
					this._DESCRIPCION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ESTADO", DbType="Bit NOT NULL")]
		public bool ESTADO
		{
			get
			{
				return this._ESTADO;
			}
			set
			{
				if ((this._ESTADO != value))
				{
					this._ESTADO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA_REGISTRO", DbType="DateTime NOT NULL")]
		public System.DateTime FECHA_REGISTRO
		{
			get
			{
				return this._FECHA_REGISTRO;
			}
			set
			{
				if ((this._FECHA_REGISTRO != value))
				{
					this._FECHA_REGISTRO = value;
				}
			}
		}
	}
	
	public partial class SP_OBTENER_RUTASResult
	{
		
		private System.Guid _GUID_RUTA;
		
		private System.Guid _GUID_EMPRESA;
		
		private string _NOMBRE_EMPRESA;
		
		private System.Nullable<System.Guid> _GUID_ZONA;
		
		private string _NOMBRE_ZONA;
		
		private string _NUMERO_RUTA;
		
		private string _NOMBRE;
		
		private System.Nullable<decimal> _TARIFA_ACTUAL;
		
		private System.Nullable<System.TimeSpan> _HORA_INICIO;
		
		private System.Nullable<System.TimeSpan> _HORA_FIN;
		
		private byte _ESTADO_SERVICIO;
		
		private System.DateTime _FECHA_REGISTRO;
		
		public SP_OBTENER_RUTASResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GUID_RUTA", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid GUID_RUTA
		{
			get
			{
				return this._GUID_RUTA;
			}
			set
			{
				if ((this._GUID_RUTA != value))
				{
					this._GUID_RUTA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GUID_EMPRESA", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid GUID_EMPRESA
		{
			get
			{
				return this._GUID_EMPRESA;
			}
			set
			{
				if ((this._GUID_EMPRESA != value))
				{
					this._GUID_EMPRESA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE_EMPRESA", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string NOMBRE_EMPRESA
		{
			get
			{
				return this._NOMBRE_EMPRESA;
			}
			set
			{
				if ((this._NOMBRE_EMPRESA != value))
				{
					this._NOMBRE_EMPRESA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GUID_ZONA", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> GUID_ZONA
		{
			get
			{
				return this._GUID_ZONA;
			}
			set
			{
				if ((this._GUID_ZONA != value))
				{
					this._GUID_ZONA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE_ZONA", DbType="NVarChar(100)")]
		public string NOMBRE_ZONA
		{
			get
			{
				return this._NOMBRE_ZONA;
			}
			set
			{
				if ((this._NOMBRE_ZONA != value))
				{
					this._NOMBRE_ZONA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NUMERO_RUTA", DbType="NVarChar(20)")]
		public string NUMERO_RUTA
		{
			get
			{
				return this._NUMERO_RUTA;
			}
			set
			{
				if ((this._NUMERO_RUTA != value))
				{
					this._NUMERO_RUTA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string NOMBRE
		{
			get
			{
				return this._NOMBRE;
			}
			set
			{
				if ((this._NOMBRE != value))
				{
					this._NOMBRE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TARIFA_ACTUAL", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> TARIFA_ACTUAL
		{
			get
			{
				return this._TARIFA_ACTUAL;
			}
			set
			{
				if ((this._TARIFA_ACTUAL != value))
				{
					this._TARIFA_ACTUAL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HORA_INICIO", DbType="Time")]
		public System.Nullable<System.TimeSpan> HORA_INICIO
		{
			get
			{
				return this._HORA_INICIO;
			}
			set
			{
				if ((this._HORA_INICIO != value))
				{
					this._HORA_INICIO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HORA_FIN", DbType="Time")]
		public System.Nullable<System.TimeSpan> HORA_FIN
		{
			get
			{
				return this._HORA_FIN;
			}
			set
			{
				if ((this._HORA_FIN != value))
				{
					this._HORA_FIN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ESTADO_SERVICIO", DbType="TinyInt NOT NULL")]
		public byte ESTADO_SERVICIO
		{
			get
			{
				return this._ESTADO_SERVICIO;
			}
			set
			{
				if ((this._ESTADO_SERVICIO != value))
				{
					this._ESTADO_SERVICIO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA_REGISTRO", DbType="DateTime NOT NULL")]
		public System.DateTime FECHA_REGISTRO
		{
			get
			{
				return this._FECHA_REGISTRO;
			}
			set
			{
				if ((this._FECHA_REGISTRO != value))
				{
					this._FECHA_REGISTRO = value;
				}
			}
		}
	}
	
	public partial class SP_OBTENER_RUTA_POR_GUIDResult
	{
		
		private System.Guid _GUID_RUTA;
		
		private System.Guid _GUID_EMPRESA;
		
		private string _NOMBRE_EMPRESA;
		
		private System.Nullable<System.Guid> _GUID_ZONA;
		
		private string _NOMBRE_ZONA;
		
		private string _NUMERO_RUTA;
		
		private string _NOMBRE;
		
		private System.Nullable<decimal> _TARIFA_ACTUAL;
		
		private System.Nullable<System.Guid> _GUID_TARIFA;
		
		private System.Nullable<System.TimeSpan> _HORA_INICIO;
		
		private System.Nullable<System.TimeSpan> _HORA_FIN;
		
		private byte _ESTADO_SERVICIO;
		
		private System.DateTime _FECHA_REGISTRO;
		
		public SP_OBTENER_RUTA_POR_GUIDResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GUID_RUTA", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid GUID_RUTA
		{
			get
			{
				return this._GUID_RUTA;
			}
			set
			{
				if ((this._GUID_RUTA != value))
				{
					this._GUID_RUTA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GUID_EMPRESA", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid GUID_EMPRESA
		{
			get
			{
				return this._GUID_EMPRESA;
			}
			set
			{
				if ((this._GUID_EMPRESA != value))
				{
					this._GUID_EMPRESA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE_EMPRESA", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string NOMBRE_EMPRESA
		{
			get
			{
				return this._NOMBRE_EMPRESA;
			}
			set
			{
				if ((this._NOMBRE_EMPRESA != value))
				{
					this._NOMBRE_EMPRESA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GUID_ZONA", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> GUID_ZONA
		{
			get
			{
				return this._GUID_ZONA;
			}
			set
			{
				if ((this._GUID_ZONA != value))
				{
					this._GUID_ZONA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE_ZONA", DbType="NVarChar(100)")]
		public string NOMBRE_ZONA
		{
			get
			{
				return this._NOMBRE_ZONA;
			}
			set
			{
				if ((this._NOMBRE_ZONA != value))
				{
					this._NOMBRE_ZONA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NUMERO_RUTA", DbType="NVarChar(20)")]
		public string NUMERO_RUTA
		{
			get
			{
				return this._NUMERO_RUTA;
			}
			set
			{
				if ((this._NUMERO_RUTA != value))
				{
					this._NUMERO_RUTA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string NOMBRE
		{
			get
			{
				return this._NOMBRE;
			}
			set
			{
				if ((this._NOMBRE != value))
				{
					this._NOMBRE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TARIFA_ACTUAL", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> TARIFA_ACTUAL
		{
			get
			{
				return this._TARIFA_ACTUAL;
			}
			set
			{
				if ((this._TARIFA_ACTUAL != value))
				{
					this._TARIFA_ACTUAL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GUID_TARIFA", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> GUID_TARIFA
		{
			get
			{
				return this._GUID_TARIFA;
			}
			set
			{
				if ((this._GUID_TARIFA != value))
				{
					this._GUID_TARIFA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HORA_INICIO", DbType="Time")]
		public System.Nullable<System.TimeSpan> HORA_INICIO
		{
			get
			{
				return this._HORA_INICIO;
			}
			set
			{
				if ((this._HORA_INICIO != value))
				{
					this._HORA_INICIO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HORA_FIN", DbType="Time")]
		public System.Nullable<System.TimeSpan> HORA_FIN
		{
			get
			{
				return this._HORA_FIN;
			}
			set
			{
				if ((this._HORA_FIN != value))
				{
					this._HORA_FIN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ESTADO_SERVICIO", DbType="TinyInt NOT NULL")]
		public byte ESTADO_SERVICIO
		{
			get
			{
				return this._ESTADO_SERVICIO;
			}
			set
			{
				if ((this._ESTADO_SERVICIO != value))
				{
					this._ESTADO_SERVICIO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA_REGISTRO", DbType="DateTime NOT NULL")]
		public System.DateTime FECHA_REGISTRO
		{
			get
			{
				return this._FECHA_REGISTRO;
			}
			set
			{
				if ((this._FECHA_REGISTRO != value))
				{
					this._FECHA_REGISTRO = value;
				}
			}
		}
	}
	
	public partial class SP_OBTENER_HORARIOS_POR_RUTAResult
	{
		
		private System.Guid _GUID_HORARIO;
		
		private System.TimeSpan _HORA_SALIDA;
		
		private byte _DIAS_SERVICIO;
		
		private bool _ESTADO;
		
		private System.DateTime _FECHA_REGISTRO;
		
		public SP_OBTENER_HORARIOS_POR_RUTAResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GUID_HORARIO", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid GUID_HORARIO
		{
			get
			{
				return this._GUID_HORARIO;
			}
			set
			{
				if ((this._GUID_HORARIO != value))
				{
					this._GUID_HORARIO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HORA_SALIDA", DbType="Time NOT NULL")]
		public System.TimeSpan HORA_SALIDA
		{
			get
			{
				return this._HORA_SALIDA;
			}
			set
			{
				if ((this._HORA_SALIDA != value))
				{
					this._HORA_SALIDA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIAS_SERVICIO", DbType="TinyInt NOT NULL")]
		public byte DIAS_SERVICIO
		{
			get
			{
				return this._DIAS_SERVICIO;
			}
			set
			{
				if ((this._DIAS_SERVICIO != value))
				{
					this._DIAS_SERVICIO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ESTADO", DbType="Bit NOT NULL")]
		public bool ESTADO
		{
			get
			{
				return this._ESTADO;
			}
			set
			{
				if ((this._ESTADO != value))
				{
					this._ESTADO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA_REGISTRO", DbType="DateTime NOT NULL")]
		public System.DateTime FECHA_REGISTRO
		{
			get
			{
				return this._FECHA_REGISTRO;
			}
			set
			{
				if ((this._FECHA_REGISTRO != value))
				{
					this._FECHA_REGISTRO = value;
				}
			}
		}
	}
	
	public partial class SP_LOGINResult
	{
		
		private System.Guid _GUID_USUARIO;
		
		private string _NOMBRE;
		
		private string _APELLIDOS;
		
		private System.Nullable<int> _ESTADO;
		
		private string _HASH_PASSWORD;
		
		public SP_LOGINResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GUID_USUARIO", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid GUID_USUARIO
		{
			get
			{
				return this._GUID_USUARIO;
			}
			set
			{
				if ((this._GUID_USUARIO != value))
				{
					this._GUID_USUARIO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string NOMBRE
		{
			get
			{
				return this._NOMBRE;
			}
			set
			{
				if ((this._NOMBRE != value))
				{
					this._NOMBRE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_APELLIDOS", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string APELLIDOS
		{
			get
			{
				return this._APELLIDOS;
			}
			set
			{
				if ((this._APELLIDOS != value))
				{
					this._APELLIDOS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ESTADO", DbType="Int")]
		public System.Nullable<int> ESTADO
		{
			get
			{
				return this._ESTADO;
			}
			set
			{
				if ((this._ESTADO != value))
				{
					this._ESTADO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HASH_PASSWORD", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string HASH_PASSWORD
		{
			get
			{
				return this._HASH_PASSWORD;
			}
			set
			{
				if ((this._HASH_PASSWORD != value))
				{
					this._HASH_PASSWORD = value;
				}
			}
		}
	}
	
	public partial class SP_OBTENER_TARIFAS_POR_RUTAResult
	{
		
		private System.Nullable<System.Guid> _GUID_TARIFA;
		
		private System.Nullable<System.Guid> _GUID_RUTA;
		
		private System.Nullable<decimal> _MONTO;
		
		private System.Nullable<System.DateTime> _FECHA_VIGENCIA;
		
		private System.Nullable<bool> _ESTADO;
		
		public SP_OBTENER_TARIFAS_POR_RUTAResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GUID_TARIFA", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> GUID_TARIFA
		{
			get
			{
				return this._GUID_TARIFA;
			}
			set
			{
				if ((this._GUID_TARIFA != value))
				{
					this._GUID_TARIFA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GUID_RUTA", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> GUID_RUTA
		{
			get
			{
				return this._GUID_RUTA;
			}
			set
			{
				if ((this._GUID_RUTA != value))
				{
					this._GUID_RUTA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MONTO", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> MONTO
		{
			get
			{
				return this._MONTO;
			}
			set
			{
				if ((this._MONTO != value))
				{
					this._MONTO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA_VIGENCIA", DbType="DateTime")]
		public System.Nullable<System.DateTime> FECHA_VIGENCIA
		{
			get
			{
				return this._FECHA_VIGENCIA;
			}
			set
			{
				if ((this._FECHA_VIGENCIA != value))
				{
					this._FECHA_VIGENCIA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ESTADO", DbType="Bit")]
		public System.Nullable<bool> ESTADO
		{
			get
			{
				return this._ESTADO;
			}
			set
			{
				if ((this._ESTADO != value))
				{
					this._ESTADO = value;
				}
			}
		}
	}
	
	public partial class SP_OBTENER_TARIFA_POR_GUIDResult
	{
		
		private System.Guid _GUID_TARIFA;
		
		private System.Guid _GUID_RUTA;
		
		private decimal _MONTO;
		
		private System.DateTime _FECHA_VIGENCIA;
		
		private bool _ESTADO;
		
		public SP_OBTENER_TARIFA_POR_GUIDResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GUID_TARIFA", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid GUID_TARIFA
		{
			get
			{
				return this._GUID_TARIFA;
			}
			set
			{
				if ((this._GUID_TARIFA != value))
				{
					this._GUID_TARIFA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GUID_RUTA", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid GUID_RUTA
		{
			get
			{
				return this._GUID_RUTA;
			}
			set
			{
				if ((this._GUID_RUTA != value))
				{
					this._GUID_RUTA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MONTO", DbType="Decimal(10,2) NOT NULL")]
		public decimal MONTO
		{
			get
			{
				return this._MONTO;
			}
			set
			{
				if ((this._MONTO != value))
				{
					this._MONTO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA_VIGENCIA", DbType="DateTime NOT NULL")]
		public System.DateTime FECHA_VIGENCIA
		{
			get
			{
				return this._FECHA_VIGENCIA;
			}
			set
			{
				if ((this._FECHA_VIGENCIA != value))
				{
					this._FECHA_VIGENCIA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ESTADO", DbType="Bit NOT NULL")]
		public bool ESTADO
		{
			get
			{
				return this._ESTADO;
			}
			set
			{
				if ((this._ESTADO != value))
				{
					this._ESTADO = value;
				}
			}
		}
	}
	
	public partial class SP_OBTENER_HORARIO_POR_GUIDResult
	{
		
		private System.Guid _GUID_HORARIO;
		
		private System.Guid _GUID_RUTA;
		
		private System.TimeSpan _HORA_SALIDA;
		
		private byte _DIAS_SERVICIO;
		
		private bool _ESTADO;
		
		public SP_OBTENER_HORARIO_POR_GUIDResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GUID_HORARIO", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid GUID_HORARIO
		{
			get
			{
				return this._GUID_HORARIO;
			}
			set
			{
				if ((this._GUID_HORARIO != value))
				{
					this._GUID_HORARIO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GUID_RUTA", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid GUID_RUTA
		{
			get
			{
				return this._GUID_RUTA;
			}
			set
			{
				if ((this._GUID_RUTA != value))
				{
					this._GUID_RUTA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HORA_SALIDA", DbType="Time NOT NULL")]
		public System.TimeSpan HORA_SALIDA
		{
			get
			{
				return this._HORA_SALIDA;
			}
			set
			{
				if ((this._HORA_SALIDA != value))
				{
					this._HORA_SALIDA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIAS_SERVICIO", DbType="TinyInt NOT NULL")]
		public byte DIAS_SERVICIO
		{
			get
			{
				return this._DIAS_SERVICIO;
			}
			set
			{
				if ((this._DIAS_SERVICIO != value))
				{
					this._DIAS_SERVICIO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ESTADO", DbType="Bit NOT NULL")]
		public bool ESTADO
		{
			get
			{
				return this._ESTADO;
			}
			set
			{
				if ((this._ESTADO != value))
				{
					this._ESTADO = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
