#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="bdMiBus")]
	public partial class ConexionLinqDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertTB_HISTORIAL_VIAJE(TB_HISTORIAL_VIAJE instance);
    partial void UpdateTB_HISTORIAL_VIAJE(TB_HISTORIAL_VIAJE instance);
    partial void DeleteTB_HISTORIAL_VIAJE(TB_HISTORIAL_VIAJE instance);
    #endregion
		
		public ConexionLinqDataContext() : 
				base(global::AccesoDatos.Properties.Settings.Default.bdMiBusConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public ConexionLinqDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ConexionLinqDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ConexionLinqDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ConexionLinqDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<TB_HISTORIAL_VIAJE> TB_HISTORIAL_VIAJE
		{
			get
			{
				return this.GetTable<TB_HISTORIAL_VIAJE>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_INGRESAR_USUARIO")]
		public int SP_INGRESAR_USUARIO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="NOMBRE", DbType="NVarChar(50)")] string nOMBRE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="APELLIDOS", DbType="NVarChar(50)")] string aPELLIDOS, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CORREO_ELECTRONICO", DbType="NVarChar(100)")] string cORREO_ELECTRONICO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PASSWORD", DbType="NVarChar(MAX)")] string pASSWORD, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NUMERO_VERIFICACION", DbType="NVarChar(MAX)")] string nUMERO_VERIFICACION, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="GUID_USUARIO", DbType="UniqueIdentifier")] ref System.Nullable<System.Guid> gUID_USUARIO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nOMBRE, aPELLIDOS, cORREO_ELECTRONICO, pASSWORD, nUMERO_VERIFICACION, gUID_USUARIO, iDRETURN, eRRORID, eRRORDESCRIPCION);
			gUID_USUARIO = ((System.Nullable<System.Guid>)(result.GetParameterValue(5)));
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(6)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(7)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(8)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_OBTENER_USUARIO")]
		public ISingleResult<SP_OBTENER_USUARIOResult> SP_OBTENER_USUARIO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="GUID_USUARIO", DbType="UniqueIdentifier")] System.Nullable<System.Guid> gUID_USUARIO)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), gUID_USUARIO);
			return ((ISingleResult<SP_OBTENER_USUARIOResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_VALIDAR_SESION")]
		public ISingleResult<SP_VALIDAR_SESIONResult> SP_VALIDAR_SESION([global::System.Data.Linq.Mapping.ParameterAttribute(Name="GUID_SESION", DbType="UniqueIdentifier")] System.Nullable<System.Guid> gUID_SESION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), gUID_SESION);
			return ((ISingleResult<SP_VALIDAR_SESIONResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_REGISTRAR_HISTORIAL")]
		public int SP_REGISTRAR_HISTORIAL([global::System.Data.Linq.Mapping.ParameterAttribute(Name="GUID_USUARIO", DbType="UniqueIdentifier")] System.Nullable<System.Guid> gUID_USUARIO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="GUID_RUTA", DbType="UniqueIdentifier")] System.Nullable<System.Guid> gUID_RUTA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="GUID_HISTORIAL", DbType="UniqueIdentifier")] ref System.Nullable<System.Guid> gUID_HISTORIAL, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), gUID_USUARIO, gUID_RUTA, gUID_HISTORIAL, iDRETURN, eRRORID, eRRORDESCRIPCION);
			gUID_HISTORIAL = ((System.Nullable<System.Guid>)(result.GetParameterValue(2)));
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(3)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(4)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(5)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_OBTENER_LISTAUSUARIOS")]
		public ISingleResult<SP_OBTENER_LISTAUSUARIOSResult> SP_OBTENER_LISTAUSUARIOS()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<SP_OBTENER_LISTAUSUARIOSResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_OBTENER_HISTORIAL_POR_USUARIO")]
		public ISingleResult<SP_OBTENER_HISTORIAL_POR_USUARIOResult> SP_OBTENER_HISTORIAL_POR_USUARIO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="GUID_USUARIO", DbType="UniqueIdentifier")] System.Nullable<System.Guid> gUID_USUARIO)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), gUID_USUARIO);
			return ((ISingleResult<SP_OBTENER_HISTORIAL_POR_USUARIOResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_OBTENER_FAVORITOS_POR_USUARIO")]
		public ISingleResult<SP_OBTENER_FAVORITOS_POR_USUARIOResult> SP_OBTENER_FAVORITOS_POR_USUARIO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="GUID_USUARIO", DbType="UniqueIdentifier")] System.Nullable<System.Guid> gUID_USUARIO)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), gUID_USUARIO);
			return ((ISingleResult<SP_OBTENER_FAVORITOS_POR_USUARIOResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_LOGIN")]
		public ISingleResult<SP_LOGINResult> SP_LOGIN([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CORREO_ELECTRONICO", DbType="NVarChar(100)")] string cORREO_ELECTRONICO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PASSWORD", DbType="NVarChar(MAX)")] string pASSWORD)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cORREO_ELECTRONICO, pASSWORD);
			return ((ISingleResult<SP_LOGINResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ELIMINAR_FAVORITO")]
		public int SP_ELIMINAR_FAVORITO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="GUID_FAVORITO", DbType="UniqueIdentifier")] System.Nullable<System.Guid> gUID_FAVORITO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), gUID_FAVORITO, iDRETURN, eRRORID, eRRORDESCRIPCION);
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(1)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(2)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(3)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_CERRAR_SESION")]
		public int SP_CERRAR_SESION([global::System.Data.Linq.Mapping.ParameterAttribute(Name="GUID_SESION", DbType="UniqueIdentifier")] System.Nullable<System.Guid> gUID_SESION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), gUID_SESION);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_AGREGAR_FAVORITO")]
		public int SP_AGREGAR_FAVORITO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="GUID_USUARIO", DbType="UniqueIdentifier")] System.Nullable<System.Guid> gUID_USUARIO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="GUID_RUTA", DbType="UniqueIdentifier")] System.Nullable<System.Guid> gUID_RUTA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="GUID_FAVORITO", DbType="UniqueIdentifier")] ref System.Nullable<System.Guid> gUID_FAVORITO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), gUID_USUARIO, gUID_RUTA, gUID_FAVORITO, iDRETURN, eRRORID, eRRORDESCRIPCION);
			gUID_FAVORITO = ((System.Nullable<System.Guid>)(result.GetParameterValue(2)));
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(3)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(4)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(5)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ABRIR_SESION")]
		public int SP_ABRIR_SESION([global::System.Data.Linq.Mapping.ParameterAttribute(Name="SESION", DbType="NVarChar(MAX)")] string sESION, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="GUID_USUARIO", DbType="UniqueIdentifier")] System.Nullable<System.Guid> gUID_USUARIO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ORIGEN", DbType="NVarChar(MAX)")] string oRIGEN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="GUID_SESION", DbType="UniqueIdentifier")] ref System.Nullable<System.Guid> gUID_SESION, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), sESION, gUID_USUARIO, oRIGEN, gUID_SESION, iDRETURN, eRRORID, eRRORDESCRIPCION);
			gUID_SESION = ((System.Nullable<System.Guid>)(result.GetParameterValue(3)));
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(4)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(5)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(6)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ACTIVAR_USUARIO")]
		public int SP_ACTIVAR_USUARIO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CORREO_ELECTRONICO", DbType="NVarChar(100)")] string cORREO_ELECTRONICO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NUMERO_VERIFICACION", DbType="NVarChar(MAX)")] string nUMERO_VERIFICACION, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FILASACTUALIZADAS", DbType="Int")] ref System.Nullable<int> fILASACTUALIZADAS, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cORREO_ELECTRONICO, nUMERO_VERIFICACION, fILASACTUALIZADAS, iDRETURN, eRRORID, eRRORDESCRIPCION);
			fILASACTUALIZADAS = ((System.Nullable<int>)(result.GetParameterValue(2)));
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(3)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(4)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(5)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_INSERTAR_BITACORA")]
		public int SP_INSERTAR_BITACORA([global::System.Data.Linq.Mapping.ParameterAttribute(Name="GUID_USUARIO", DbType="UniqueIdentifier")] System.Nullable<System.Guid> gUID_USUARIO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CLASE", DbType="NVarChar(100)")] string cLASE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="METODO", DbType="NVarChar(100)")] string mETODO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TIPO", DbType="SmallInt")] System.Nullable<short> tIPO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CODIGO_ERROR", DbType="Int")] System.Nullable<int> cODIGO_ERROR, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DESCRIPCION", DbType="NVarChar(MAX)")] string dESCRIPCION, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="REQUEST", DbType="NVarChar(MAX)")] string rEQUEST, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="RESPONSE", DbType="NVarChar(MAX)")] string rESPONSE)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), gUID_USUARIO, cLASE, mETODO, tIPO, cODIGO_ERROR, dESCRIPCION, rEQUEST, rESPONSE);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ELIMINAR_USUARIO")]
		public int SP_ELIMINAR_USUARIO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="GUID_USUARIO", DbType="UniqueIdentifier")] System.Nullable<System.Guid> gUID_USUARIO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), gUID_USUARIO, iDRETURN, eRRORID, eRRORDESCRIPCION);
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(1)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(2)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(3)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_DESACTIVAR_USUARIO")]
		public int SP_DESACTIVAR_USUARIO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="GUID_USUARIO", DbType="UniqueIdentifier")] System.Nullable<System.Guid> gUID_USUARIO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), gUID_USUARIO, iDRETURN, eRRORID, eRRORDESCRIPCION);
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(1)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(2)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(3)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ACTUALIZAR_USUARIO")]
		public int SP_ACTUALIZAR_USUARIO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="GUID_USUARIO", DbType="UniqueIdentifier")] System.Nullable<System.Guid> gUID_USUARIO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NOMBRE", DbType="NVarChar(50)")] string nOMBRE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="APELLIDOS", DbType="NVarChar(50)")] string aPELLIDOS, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), gUID_USUARIO, nOMBRE, aPELLIDOS, iDRETURN, eRRORID, eRRORDESCRIPCION);
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(3)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(4)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(5)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_OBTENER_PARADA_POR_GUID")]
		public ISingleResult<SP_OBTENER_PARADA_POR_GUIDResult> SP_OBTENER_PARADA_POR_GUID([global::System.Data.Linq.Mapping.ParameterAttribute(Name="GUID_PARADA", DbType="UniqueIdentifier")] System.Nullable<System.Guid> gUID_PARADA)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), gUID_PARADA);
			return ((ISingleResult<SP_OBTENER_PARADA_POR_GUIDResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_OBTENER_PARADAS_POR_RUTA")]
		public ISingleResult<SP_OBTENER_PARADAS_POR_RUTAResult> SP_OBTENER_PARADAS_POR_RUTA([global::System.Data.Linq.Mapping.ParameterAttribute(Name="GUID_RUTA", DbType="UniqueIdentifier")] System.Nullable<System.Guid> gUID_RUTA)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), gUID_RUTA);
			return ((ISingleResult<SP_OBTENER_PARADAS_POR_RUTAResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TB_HISTORIAL_VIAJE")]
	public partial class TB_HISTORIAL_VIAJE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_HISTORIAL;
		
		private System.Guid _GUID_HISTORIAL;
		
		private long _ID_USUARIO;
		
		private int _ID_RUTA;
		
		private System.Nullable<int> _ID_TARIFA;
		
		private System.DateTime _FECHA_CONSULTA;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_HISTORIALChanging(int value);
    partial void OnID_HISTORIALChanged();
    partial void OnGUID_HISTORIALChanging(System.Guid value);
    partial void OnGUID_HISTORIALChanged();
    partial void OnID_USUARIOChanging(long value);
    partial void OnID_USUARIOChanged();
    partial void OnID_RUTAChanging(int value);
    partial void OnID_RUTAChanged();
    partial void OnID_TARIFAChanging(System.Nullable<int> value);
    partial void OnID_TARIFAChanged();
    partial void OnFECHA_CONSULTAChanging(System.DateTime value);
    partial void OnFECHA_CONSULTAChanged();
    #endregion
		
		public TB_HISTORIAL_VIAJE()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_HISTORIAL", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_HISTORIAL
		{
			get
			{
				return this._ID_HISTORIAL;
			}
			set
			{
				if ((this._ID_HISTORIAL != value))
				{
					this.OnID_HISTORIALChanging(value);
					this.SendPropertyChanging();
					this._ID_HISTORIAL = value;
					this.SendPropertyChanged("ID_HISTORIAL");
					this.OnID_HISTORIALChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GUID_HISTORIAL", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid GUID_HISTORIAL
		{
			get
			{
				return this._GUID_HISTORIAL;
			}
			set
			{
				if ((this._GUID_HISTORIAL != value))
				{
					this.OnGUID_HISTORIALChanging(value);
					this.SendPropertyChanging();
					this._GUID_HISTORIAL = value;
					this.SendPropertyChanged("GUID_HISTORIAL");
					this.OnGUID_HISTORIALChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_USUARIO", DbType="BigInt NOT NULL")]
		public long ID_USUARIO
		{
			get
			{
				return this._ID_USUARIO;
			}
			set
			{
				if ((this._ID_USUARIO != value))
				{
					this.OnID_USUARIOChanging(value);
					this.SendPropertyChanging();
					this._ID_USUARIO = value;
					this.SendPropertyChanged("ID_USUARIO");
					this.OnID_USUARIOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_RUTA", DbType="Int NOT NULL")]
		public int ID_RUTA
		{
			get
			{
				return this._ID_RUTA;
			}
			set
			{
				if ((this._ID_RUTA != value))
				{
					this.OnID_RUTAChanging(value);
					this.SendPropertyChanging();
					this._ID_RUTA = value;
					this.SendPropertyChanged("ID_RUTA");
					this.OnID_RUTAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_TARIFA", DbType="Int")]
		public System.Nullable<int> ID_TARIFA
		{
			get
			{
				return this._ID_TARIFA;
			}
			set
			{
				if ((this._ID_TARIFA != value))
				{
					this.OnID_TARIFAChanging(value);
					this.SendPropertyChanging();
					this._ID_TARIFA = value;
					this.SendPropertyChanged("ID_TARIFA");
					this.OnID_TARIFAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA_CONSULTA", DbType="DateTime NOT NULL")]
		public System.DateTime FECHA_CONSULTA
		{
			get
			{
				return this._FECHA_CONSULTA;
			}
			set
			{
				if ((this._FECHA_CONSULTA != value))
				{
					this.OnFECHA_CONSULTAChanging(value);
					this.SendPropertyChanging();
					this._FECHA_CONSULTA = value;
					this.SendPropertyChanged("FECHA_CONSULTA");
					this.OnFECHA_CONSULTAChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class SP_OBTENER_USUARIOResult
	{
		
		private System.Guid _GUID_USUARIO;
		
		private string _NOMBRE;
		
		private string _APELLIDOS;
		
		private string _CORREO_ELECTRONICO;
		
		private System.DateTime _FECHA_REGISTRO;
		
		private System.Nullable<int> _ESTADO;
		
		public SP_OBTENER_USUARIOResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GUID_USUARIO", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid GUID_USUARIO
		{
			get
			{
				return this._GUID_USUARIO;
			}
			set
			{
				if ((this._GUID_USUARIO != value))
				{
					this._GUID_USUARIO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string NOMBRE
		{
			get
			{
				return this._NOMBRE;
			}
			set
			{
				if ((this._NOMBRE != value))
				{
					this._NOMBRE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_APELLIDOS", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string APELLIDOS
		{
			get
			{
				return this._APELLIDOS;
			}
			set
			{
				if ((this._APELLIDOS != value))
				{
					this._APELLIDOS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CORREO_ELECTRONICO", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string CORREO_ELECTRONICO
		{
			get
			{
				return this._CORREO_ELECTRONICO;
			}
			set
			{
				if ((this._CORREO_ELECTRONICO != value))
				{
					this._CORREO_ELECTRONICO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA_REGISTRO", DbType="DateTime NOT NULL")]
		public System.DateTime FECHA_REGISTRO
		{
			get
			{
				return this._FECHA_REGISTRO;
			}
			set
			{
				if ((this._FECHA_REGISTRO != value))
				{
					this._FECHA_REGISTRO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ESTADO", DbType="Int")]
		public System.Nullable<int> ESTADO
		{
			get
			{
				return this._ESTADO;
			}
			set
			{
				if ((this._ESTADO != value))
				{
					this._ESTADO = value;
				}
			}
		}
	}
	
	public partial class SP_VALIDAR_SESIONResult
	{
		
		private System.Guid _GUID_SESION;
		
		private System.Guid _GUID_USUARIO;
		
		private string _NOMBRE;
		
		private string _APELLIDOS;
		
		private bool _ESTADO;
		
		public SP_VALIDAR_SESIONResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GUID_SESION", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid GUID_SESION
		{
			get
			{
				return this._GUID_SESION;
			}
			set
			{
				if ((this._GUID_SESION != value))
				{
					this._GUID_SESION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GUID_USUARIO", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid GUID_USUARIO
		{
			get
			{
				return this._GUID_USUARIO;
			}
			set
			{
				if ((this._GUID_USUARIO != value))
				{
					this._GUID_USUARIO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string NOMBRE
		{
			get
			{
				return this._NOMBRE;
			}
			set
			{
				if ((this._NOMBRE != value))
				{
					this._NOMBRE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_APELLIDOS", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string APELLIDOS
		{
			get
			{
				return this._APELLIDOS;
			}
			set
			{
				if ((this._APELLIDOS != value))
				{
					this._APELLIDOS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ESTADO", DbType="Bit NOT NULL")]
		public bool ESTADO
		{
			get
			{
				return this._ESTADO;
			}
			set
			{
				if ((this._ESTADO != value))
				{
					this._ESTADO = value;
				}
			}
		}
	}
	
	public partial class SP_OBTENER_LISTAUSUARIOSResult
	{
		
		private System.Guid _GUID_USUARIO;
		
		private string _NOMBRE;
		
		private string _APELLIDOS;
		
		private string _CORREO_ELECTRONICO;
		
		private System.DateTime _FECHA_REGISTRO;
		
		public SP_OBTENER_LISTAUSUARIOSResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GUID_USUARIO", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid GUID_USUARIO
		{
			get
			{
				return this._GUID_USUARIO;
			}
			set
			{
				if ((this._GUID_USUARIO != value))
				{
					this._GUID_USUARIO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string NOMBRE
		{
			get
			{
				return this._NOMBRE;
			}
			set
			{
				if ((this._NOMBRE != value))
				{
					this._NOMBRE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_APELLIDOS", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string APELLIDOS
		{
			get
			{
				return this._APELLIDOS;
			}
			set
			{
				if ((this._APELLIDOS != value))
				{
					this._APELLIDOS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CORREO_ELECTRONICO", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string CORREO_ELECTRONICO
		{
			get
			{
				return this._CORREO_ELECTRONICO;
			}
			set
			{
				if ((this._CORREO_ELECTRONICO != value))
				{
					this._CORREO_ELECTRONICO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA_REGISTRO", DbType="DateTime NOT NULL")]
		public System.DateTime FECHA_REGISTRO
		{
			get
			{
				return this._FECHA_REGISTRO;
			}
			set
			{
				if ((this._FECHA_REGISTRO != value))
				{
					this._FECHA_REGISTRO = value;
				}
			}
		}
	}
	
	public partial class SP_OBTENER_HISTORIAL_POR_USUARIOResult
	{
		
		private System.Guid _GUID_HISTORIAL;
		
		private System.Guid _GUID_RUTA;
		
		private string _NOMBRE_RUTA;
		
		private System.Nullable<decimal> _TARIFA_CONSULTADA;
		
		private System.DateTime _FECHA_CONSULTA;
		
		public SP_OBTENER_HISTORIAL_POR_USUARIOResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GUID_HISTORIAL", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid GUID_HISTORIAL
		{
			get
			{
				return this._GUID_HISTORIAL;
			}
			set
			{
				if ((this._GUID_HISTORIAL != value))
				{
					this._GUID_HISTORIAL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GUID_RUTA", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid GUID_RUTA
		{
			get
			{
				return this._GUID_RUTA;
			}
			set
			{
				if ((this._GUID_RUTA != value))
				{
					this._GUID_RUTA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE_RUTA", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string NOMBRE_RUTA
		{
			get
			{
				return this._NOMBRE_RUTA;
			}
			set
			{
				if ((this._NOMBRE_RUTA != value))
				{
					this._NOMBRE_RUTA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TARIFA_CONSULTADA", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> TARIFA_CONSULTADA
		{
			get
			{
				return this._TARIFA_CONSULTADA;
			}
			set
			{
				if ((this._TARIFA_CONSULTADA != value))
				{
					this._TARIFA_CONSULTADA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA_CONSULTA", DbType="DateTime NOT NULL")]
		public System.DateTime FECHA_CONSULTA
		{
			get
			{
				return this._FECHA_CONSULTA;
			}
			set
			{
				if ((this._FECHA_CONSULTA != value))
				{
					this._FECHA_CONSULTA = value;
				}
			}
		}
	}
	
	public partial class SP_OBTENER_FAVORITOS_POR_USUARIOResult
	{
		
		private System.Guid _GUID_FAVORITO;
		
		private System.Guid _GUID_RUTA;
		
		private string _NOMBRE_RUTA;
		
		private System.Nullable<decimal> _TARIFA_ACTUAL;
		
		private System.DateTime _FECHA_REGISTRO;
		
		public SP_OBTENER_FAVORITOS_POR_USUARIOResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GUID_FAVORITO", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid GUID_FAVORITO
		{
			get
			{
				return this._GUID_FAVORITO;
			}
			set
			{
				if ((this._GUID_FAVORITO != value))
				{
					this._GUID_FAVORITO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GUID_RUTA", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid GUID_RUTA
		{
			get
			{
				return this._GUID_RUTA;
			}
			set
			{
				if ((this._GUID_RUTA != value))
				{
					this._GUID_RUTA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE_RUTA", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string NOMBRE_RUTA
		{
			get
			{
				return this._NOMBRE_RUTA;
			}
			set
			{
				if ((this._NOMBRE_RUTA != value))
				{
					this._NOMBRE_RUTA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TARIFA_ACTUAL", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> TARIFA_ACTUAL
		{
			get
			{
				return this._TARIFA_ACTUAL;
			}
			set
			{
				if ((this._TARIFA_ACTUAL != value))
				{
					this._TARIFA_ACTUAL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA_REGISTRO", DbType="DateTime NOT NULL")]
		public System.DateTime FECHA_REGISTRO
		{
			get
			{
				return this._FECHA_REGISTRO;
			}
			set
			{
				if ((this._FECHA_REGISTRO != value))
				{
					this._FECHA_REGISTRO = value;
				}
			}
		}
	}
	
	public partial class SP_LOGINResult
	{
		
		private System.Guid _GUID_USUARIO;
		
		private string _NOMBRE;
		
		private string _APELLIDOS;
		
		private System.Nullable<int> _ESTADO;
		
		public SP_LOGINResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GUID_USUARIO", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid GUID_USUARIO
		{
			get
			{
				return this._GUID_USUARIO;
			}
			set
			{
				if ((this._GUID_USUARIO != value))
				{
					this._GUID_USUARIO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string NOMBRE
		{
			get
			{
				return this._NOMBRE;
			}
			set
			{
				if ((this._NOMBRE != value))
				{
					this._NOMBRE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_APELLIDOS", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string APELLIDOS
		{
			get
			{
				return this._APELLIDOS;
			}
			set
			{
				if ((this._APELLIDOS != value))
				{
					this._APELLIDOS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ESTADO", DbType="Int")]
		public System.Nullable<int> ESTADO
		{
			get
			{
				return this._ESTADO;
			}
			set
			{
				if ((this._ESTADO != value))
				{
					this._ESTADO = value;
				}
			}
		}
	}
	
	public partial class SP_OBTENER_PARADA_POR_GUIDResult
	{
		
		private System.Guid _GUID_PARADA;
		
		private string _NOMBRE;
		
		private string _DESCRIPCION;
		
		private System.Nullable<decimal> _LATITUD;
		
		private System.Nullable<decimal> _LONGITUD;
		
		private bool _ESTADO;
		
		private System.DateTime _FECHA_REGISTRO;
		
		public SP_OBTENER_PARADA_POR_GUIDResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GUID_PARADA", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid GUID_PARADA
		{
			get
			{
				return this._GUID_PARADA;
			}
			set
			{
				if ((this._GUID_PARADA != value))
				{
					this._GUID_PARADA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string NOMBRE
		{
			get
			{
				return this._NOMBRE;
			}
			set
			{
				if ((this._NOMBRE != value))
				{
					this._NOMBRE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DESCRIPCION", DbType="NVarChar(MAX)")]
		public string DESCRIPCION
		{
			get
			{
				return this._DESCRIPCION;
			}
			set
			{
				if ((this._DESCRIPCION != value))
				{
					this._DESCRIPCION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LATITUD", DbType="Decimal(10,7)")]
		public System.Nullable<decimal> LATITUD
		{
			get
			{
				return this._LATITUD;
			}
			set
			{
				if ((this._LATITUD != value))
				{
					this._LATITUD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LONGITUD", DbType="Decimal(10,7)")]
		public System.Nullable<decimal> LONGITUD
		{
			get
			{
				return this._LONGITUD;
			}
			set
			{
				if ((this._LONGITUD != value))
				{
					this._LONGITUD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ESTADO", DbType="Bit NOT NULL")]
		public bool ESTADO
		{
			get
			{
				return this._ESTADO;
			}
			set
			{
				if ((this._ESTADO != value))
				{
					this._ESTADO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA_REGISTRO", DbType="DateTime NOT NULL")]
		public System.DateTime FECHA_REGISTRO
		{
			get
			{
				return this._FECHA_REGISTRO;
			}
			set
			{
				if ((this._FECHA_REGISTRO != value))
				{
					this._FECHA_REGISTRO = value;
				}
			}
		}
	}
	
	public partial class SP_OBTENER_PARADAS_POR_RUTAResult
	{
		
		private System.Guid _GUID_PARADA;
		
		private string _NOMBRE;
		
		private string _DESCRIPCION;
		
		private System.Nullable<decimal> _LATITUD;
		
		private System.Nullable<decimal> _LONGITUD;
		
		private int _ORDEN;
		
		public SP_OBTENER_PARADAS_POR_RUTAResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GUID_PARADA", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid GUID_PARADA
		{
			get
			{
				return this._GUID_PARADA;
			}
			set
			{
				if ((this._GUID_PARADA != value))
				{
					this._GUID_PARADA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string NOMBRE
		{
			get
			{
				return this._NOMBRE;
			}
			set
			{
				if ((this._NOMBRE != value))
				{
					this._NOMBRE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DESCRIPCION", DbType="NVarChar(MAX)")]
		public string DESCRIPCION
		{
			get
			{
				return this._DESCRIPCION;
			}
			set
			{
				if ((this._DESCRIPCION != value))
				{
					this._DESCRIPCION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LATITUD", DbType="Decimal(10,7)")]
		public System.Nullable<decimal> LATITUD
		{
			get
			{
				return this._LATITUD;
			}
			set
			{
				if ((this._LATITUD != value))
				{
					this._LATITUD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LONGITUD", DbType="Decimal(10,7)")]
		public System.Nullable<decimal> LONGITUD
		{
			get
			{
				return this._LONGITUD;
			}
			set
			{
				if ((this._LONGITUD != value))
				{
					this._LONGITUD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ORDEN", DbType="Int NOT NULL")]
		public int ORDEN
		{
			get
			{
				return this._ORDEN;
			}
			set
			{
				if ((this._ORDEN != value))
				{
					this._ORDEN = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
