<?xml version="1.0" encoding="utf-8"?><Database Name="bdMiBus" Class="ConexionLinqDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=localhost;Initial Catalog=bdMiBus;Integrated Security=True;Trust Server Certificate=True" SettingsObjectName="AccesoDatos.Properties.Settings" SettingsPropertyName="bdMiBusConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.TB_HISTORIAL_VIAJE" Member="TB_HISTORIAL_VIAJE">
    <Type Name="TB_HISTORIAL_VIAJE">
      <Column Name="ID_HISTORIAL" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="GUID_HISTORIAL" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="ID_USUARIO" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="ID_RUTA" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ID_TARIFA" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FECHA_CONSULTA" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Function Name="dbo.SP_REGISTRAR_HISTORIAL" Method="SP_REGISTRAR_HISTORIAL">
    <Parameter Name="GUID_USUARIO" Parameter="gUID_USUARIO" Type="System.Guid" DbType="UniqueIdentifier" />
    <Parameter Name="GUID_RUTA" Parameter="gUID_RUTA" Type="System.Guid" DbType="UniqueIdentifier" />
    <Parameter Name="GUID_HISTORIAL" Parameter="gUID_HISTORIAL" Type="System.Guid" DbType="UniqueIdentifier" Direction="InOut" />
    <Parameter Name="IDRETURN" Parameter="iDRETURN" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="ERRORID" Parameter="eRRORID" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="ERRORDESCRIPCION" Parameter="eRRORDESCRIPCION" Type="System.String" DbType="NVarChar(MAX)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
</Database>