-- Script SQL de ejemplo para crear stored procedures que manejen geography

-- SP para crear una parada con coordenadas
CREATE PROCEDURE SP_CREAR_PARADA
    @GUID_PARADA UNIQUEIDENTIFIER,
    @NOMBRE NVARCHAR(100),
    @DESCRIPCION NVARCHAR(500),
    @LATITUD FLOAT,
    @LONGITUD FLOAT,
    @ESTADO BIT,
    @IDRETURN INT OUTPUT,
    @ERRORID INT OUTPUT,
    @ERRORDESCRIPCION NVARCHAR(MAX) OUTPUT
AS
BEGIN
    SET NOCOUNT ON;

    BEGIN TRY
        -- Crear el punto geography desde lat/long
        DECLARE @UBICACION GEOGRAPHY = geography::Point(@LATITUD, @LONGITUD, 4326);

        INSERT INTO TB_PARADA (GUID_PARADA, NOMBRE, DESCRIPCION, LATITUD, LONGITUD, UBICACION, ESTADO, FECHA_REGISTRO)
        VALUES (@GUID_PARADA, @NOMBRE, @DESCRIPCION, @LATITUD, @LONGITUD, @UBICACION, @ESTADO, GETDATE());

        SET @IDRETURN = SCOPE_IDENTITY();
        SET @ERRORID = 0;
        SET @ERRORDESCRIPCION = 'Parada creada exitosamente';

    END TRY
    BEGIN CATCH
        SET @IDRETURN = -1;
        SET @ERRORID = ERROR_NUMBER();
        SET @ERRORDESCRIPCION = ERROR_MESSAGE();
    END CATCH
END
GO

-- SP para obtener paradas dentro de un radio (en metros)
CREATE PROCEDURE SP_OBTENER_PARADAS_CERCANAS
    @LATITUD FLOAT,
    @LONGITUD FLOAT,
    @RADIO_METROS FLOAT = 1000 -- Por defecto 1km
AS
BEGIN
    SET NOCOUNT ON;

    DECLARE @PUNTO_REFERENCIA GEOGRAPHY = geography::Point(@LATITUD, @LONGITUD, 4326);

    SELECT 
        GUID_PARADA,
        NOMBRE,
        DESCRIPCION,
        LATITUD,
        LONGITUD,
        ESTADO,
        FECHA_REGISTRO,
        @PUNTO_REFERENCIA.STDistance(UBICACION) AS DISTANCIA_METROS
    FROM TB_PARADA
    WHERE ESTADO = 1
        AND @PUNTO_REFERENCIA.STDistance(UBICACION) <= @RADIO_METROS
    ORDER BY DISTANCIA_METROS;
END
GO

-- SP para actualizar ubicación de una parada
CREATE PROCEDURE SP_ACTUALIZAR_UBICACION_PARADA
    @GUID_PARADA UNIQUEIDENTIFIER,
    @LATITUD FLOAT,
    @LONGITUD FLOAT,
    @ERRORID INT OUTPUT,
    @ERRORDESCRIPCION NVARCHAR(MAX) OUTPUT
AS
BEGIN
    SET NOCOUNT ON;

    BEGIN TRY
        DECLARE @UBICACION GEOGRAPHY = geography::Point(@LATITUD, @LONGITUD, 4326);

        UPDATE TB_PARADA
        SET LATITUD = @LATITUD,
            LONGITUD = @LONGITUD,
            UBICACION = @UBICACION
        WHERE GUID_PARADA = @GUID_PARADA;

        SET @ERRORID = 0;
        SET @ERRORDESCRIPCION = 'Ubicación actualizada exitosamente';

    END TRY
    BEGIN CATCH
        SET @ERRORID = ERROR_NUMBER();
        SET @ERRORDESCRIPCION = ERROR_MESSAGE();
    END CATCH
END
GO
